### ISSUE TITLE
create redirect on benefit-tool.usa.gov/* to point to /benefit-finder/*

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/usagov-benefits-eligibility#1012]
## Background
We are in the process of migrating our subdomain DNS record over to usagov. Until pages removes our `benefit-tool` record we can redirect traffic using our node application.

## Acceptance Criteria
good: `benefit-tool.usa.gov/*` 301 redirects to `usa.gov/benefit-finder`
best:  all these mappings are redirected https://docs.google.com/spreadsheets/d/1IDivDsQPVZ2XVPFpeG1WJEEupVYVUtjn7lNidjsZh1A/edit#gid=0

**Comment by scottqueen-bixal** [comment]
Node Redirects have been step on pages staging site in preparation for launch tomorrow.

Current | New
-- | --
https://benefits-tool-demo.usa.gov/ | https://usa.gov/benefit-finder
https://benefits-tool-demo.usa.gov/death-of-a-loved-one | https://usa.gov/benefit-finder/death
https://benefits-tool-demo.usa.gov/disability | https://usa.gov/benefit-finder/disability
https://benefits-tool-demo.usa.gov/retirement | https://usa.gov/benefit-finder/retirement
https://benefits-tool-demo.usa.gov/es | http://usa.gov/es/buscador-beneficios
https://benefits-tool-demo.usa.gov/es/death-of-a-loved-one |https://usa.gov/es/buscador-beneficios/muerte
https://benefits-tool-demo.usa.gov/es/retirement | https://usa.gov/es/buscador-beneficios/jubilacion
https://benefits-tool-demo.usa.gov/es/disability | https://usa.gov/es/buscador-beneficios/discapacidad

**Comment by scottqueen-bixal** [comment]
Node Redirects have been updated on production

Current | New
-- | --
https://benefits-tool.usa.gov/ | https://usa.gov/benefit-finder
https://benefits-tool.usa.gov/death-of-a-loved-one | https://usa.gov/benefit-finder/death
https://benefits-tool.usa.gov/disability | https://usa.gov/benefit-finder/disability
https://benefits-tool.usa.gov/retirement | https://usa.gov/benefit-finder/retirement
https://benefits-tool.usa.gov/es | http://usa.gov/es/buscador-beneficios
https://benefits-tool.usa.gov/es/death-of-a-loved-one |https://usa.gov/es/buscador-beneficios/muerte
https://benefits-tool.usa.gov/es/retirement | https://usa.gov/es/buscador-beneficios/jubilacion
https://benefits-tool.usa.gov/es/disability | https://usa.gov/es/buscador-beneficios/discapacidad

**Comment by nehemiah-abuga** [comment]
@scottqueen-bixal  - I have validated this in PROD and this works as expected.
