### ISSUE TITLE
Selecting key eligibility criteria

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#158]
As a BEARS site user, in order conveniently browse all benefits and efficiently identify benefits I might be eligible for, I would like to be able to select key eligibility criteria that applies to me within the benefit card.

Acceptance criteria:

- [x] The user can select key eligibility criteria within the benefit card
- [x] The relevant benefits are resorted based on the selections within the card
- [x] Key eligibility criteria selections within the benefit card are reflected on the left-rail criteria filters (does not apply to virtual criteria)

Definition of Done:
- [x] Code complete
- [x] Security scans passed
- [x] QA tested
- [x] Accessibility tested
- [x] Deployed to staging
- [x] PR approved / Peer reviewed
- [x] PO approved

[BEARS P4 Definition of Done](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit)

**Comment by wesley-dean-flexion** [comment]
@r-bartlett-gsa what does this mean:
> (does not apply to virtual criteria)

**Comment by r-bartlett-gsa** [comment]
@wesley-dean-gsa The criteria that is assigned to the benefit but not to the life event that the benefit belongs to is virtual criteria. In another words it's a criteria that is only displayed within the benefit card, but it's not displayed as a filter on the left-rail.

**Comment by wesley-dean-gsa** [comment]
Got it.  Thanks!!
