### ISSUE TITLE
SPIKE: Design Opportunities

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#163]
1. Explore landing page card design options to improve visual appeal and functionality (for example, [American Rescue Plan](https://www.whitehouse.gov/american-rescue-plan/) page).
2. To help guide the user within BEARS, show an expanded subnav tray that highlights the life event or benefit type page the user is on, and exposes other life events/types that are available. See [Figma file](https://www.figma.com/file/AA5HrSnoiG7cnU4nME9bWY/BEARS-UI-design?node-id=0%3A1) as an example (Main nav exploration 9/7/21)
3. Addition of another form of distinction between benefits that the user might be eligible for, might not be eligible and the ‘unknowns’.
4. Explore options for a different dropdown field treatment: Radio buttons if there are less than 7 choices. (see #158 )
5. Update default dropdown field label.
6. Addition of headers to the left (eligibility criteria questions) and right (benefits results) sections on the life event pages to visually distinguish the two sections.
7. Update print styling to enhance readability and usability of a printed version.
8. User dashboard to save criteria selections and benefits

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr and @maomeara63 See item #5 above. This is something that came during Phase 3, but did not proceed with any changes. Perhaps the issue with dropdowns in the card would be solved if we moved to checkboxes instead of dropdowns if there are less than 7 choices. In that case we need to ensure that the layout on the left rail (and in the benefit card) does not introduce more confusion to the user. This is something we can discuss at out working session.

**Comment by fpigeonjr** [comment]
1. [First pass](https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/screen/932635ef-6772-4ce0-a254-621434ba2751) on benefit cards on homepage
2. First pass on [breadcrumbs](https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/screen/6009ef8a-49e8-4f43-a9de-d5ec1aa5df93) or [megamenu](https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/screen/a187a1e8-bee5-4700-922b-bd883d35e5f9) options.
3. Maybe a [minimal colored border](https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/screen/6009ef8a-49e8-4f43-a9de-d5ec1aa5df93) could work. 
4. Closed
5. Note sure on this one but `- Select -` is the default from [uswds dropdown](https://designsystem.digital.gov/components/dropdown/).
6. Added a heading on mobile for Benefits Cards section but not happy with any attempts on desktop.
7. This probably needs to be a user-story for the backlog.
8. This probably needs to be a user-story for the backlog.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Here's my initial feedback, and we can chat more about it tomorrow:
1. I like both options, dark blue cards and the ones with the images. And it's great to have both options so we can test with users. 
2. I'm not feeling the breadcrumbs, as the breadcrumbs are intended to indicate the path the user took. Showing all life events in a linear row, like breadcrumbs, seems confusing. For the megamenu, I like how it looks like and that the user is able to get to another life event quickly, but we need to think about how the users will get to All Life Events page, since clicking on Benefits by life event will expand the menu.
3. I like that a lot!
4. Closed closed :) 
5. I think we can hold off on that one.
6. We can leave this one as is for now: no changes on desktop, and Results header only on mobile.
7. I'll setup a new user story for this.
8. This was de-prioritized for the moment, but also will setup a new user story.

**Comment by fpigeonjr** [comment]
> @fpigeonjr Here's my initial feedback, and we can chat more about it tomorrow:
Thanks for that @r-bartlett-gsa , I think it this will enable us to have a good conversation tomorrow.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr All items either have a separate user story or are placed on hold. I think we can move this card to Done.

**Comment by fpigeonjr** [comment]
Sounds good @r-bartlett-gsa.
