### ISSUE TITLE
New Data Field (Date)

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#164]
As a BEARS site user, in order to get an accurate list of benefits which I might be eligible for based on my information, I would like to provide date information for benefits that have date as one of the eligibility requirements (example, date of birth or date of death).

Acceptance Criteria:

- The user can input date information on the life event page under left-hand-rail filters
- The date information is used by the system to calculate and validate eligibility requirements

Date requirement calculation considerations:

- duration in relationship to today's date (for example, applicant's age, or funeral took place less xx years). Benefit examples are [CMS's Medicare with Retirement](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/site/gsa/usagov-benefits-eligibility/agencies/centers-for-medicare-and-medicaid) or [SSA's Lump-Sum Death Benefit](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/site/gsa/usagov-benefits-eligibility/agencies/social-security-administration)
- provided date is before/after a certain date. Benefit examples are [FEMA's COVID-19 Funeral Assistance](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/site/gsa/usagov-benefits-eligibility/agencies/fema) or [DOD's Annuity for Certain Military Surviving Spouses](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/site/gsa/usagov-benefits-eligibility/agencies/department-of-defense)

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [ ] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [ ] Usability testing
- [x] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 Overall the date works great, so good job!! And I only have a few feedback items for you.

- After clearing the selections, the date field is not cleared: https://www.screencast.com/t/EmXmjEqbjfib Clearing Selections should remove the user's input from the date field.
- In the benefit card, when the eligibility is calculated, only the label should be highlighted (red or green) but not the input field.

---

- This comment is just for the record, but does not need to be addressed at the moment, because we might want to remove input fields from the benefit cards in the near future. When the date is entered in the left rail, it is not copied over in the benefit card; and when the date is entered in the benefit card, it is not copied over to the left rail.

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 Just want to make sure that you aware that this feedback item does not need to be addressed at the moment, since the functionality to interact with criteria within the benefit card might go away:

> This comment is just for the record, but does not need to be addressed at the moment, because we might want to remove input fields from the benefit cards in the near future. When the date is entered in the left rail, it is not copied over in the benefit card; and when the date is entered in the benefit card, it is not copied over to the left rail.

**Comment by lgarceau768** [comment]
@r-bartlett-gsa I have addressed the bugs laid out above, could you please confirm that they are no longer present?

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 In addition to the above feedback, I think there should also be some sort of date validation and error messaging for the dates that are invalid, for example the user should not be able to enter future dates (https://www.screencast.com/t/i1kjaEUoM9) or dates that don't exists (https://www.screencast.com/t/1IQDsm5ZM)

**Comment by lgarceau768** [comment]
> * a
@r-bartlett-gsa  The virtual criteria issue is because the acceptable values within `fema-covid-funeral-assistance.md` that is associated with the `deceased_date_of_funeral` criteria key has not been changed from `true` to a valid date.

**Comment by r-bartlett-gsa** [comment]
Thank you @lgarceau768 and apologies for the oversight with the FEMA benefit content. 

And I also should have been more clear about this. The date label should be bold on the **left-hand rail**: https://www.screencast.com/t/kzePX7Sn

> - And let's make the label bold, so it matches the styling of other criteria types.

**Comment by r-bartlett-gsa** [comment]
An update on the following feedback item:

> @lgarceau768 In addition to the above feedback, I think there should also be some sort of date validation and error messaging for the dates that are invalid, for example the user should not be able to enter future dates (https://www.screencast.com/t/i1kjaEUoM9) or dates that don't exists (https://www.screencast.com/t/1IQDsm5ZM)

When an invalid date is entered, an error message is shown to indicate that, and the system does not check if the eligibility is met for the benefits with that date criteria.

**Comment by lgarceau768** [comment]
> An update on the following feedback item:
> 
> > @lgarceau768 In addition to the above feedback, I think there should also be some sort of date validation and error messaging for the dates that are invalid, for example the user should not be able to enter future dates (https://www.screencast.com/t/i1kjaEUoM9) or dates that don't exists (https://www.screencast.com/t/1IQDsm5ZM)
> 
> When an invalid date is entered, an error message is shown to indicate that, and the system does not check if the eligibility is met for the benefits with that date criteria.

Yes with the latest fix they will not check for eligibility.

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 Just documenting the issue that still needs to be resolved. If a valid date is entered and the benefits are estimated, but then the date is changed to invalid, the previous valid date still persists in URL and benefits estimation is not updated. See: https://www.screencast.com/t/5mNlWh32bNn

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 When an invalid date is entered, the entry remains in the input field and an error message is displayed, eligibility is not validated. This is correct and expected behavior.

When an invalid date is entered, after a valid date was entered, currently the entry is removed from the input fields and an error message is displayed. The invalid date needs to remain in the field until it's cleared or overwritten with something else.

https://www.screencast.com/t/fUqhpyOixvS
