### ISSUE TITLE
Top-level eligibility questions - Frontend

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#167]
As a BEARS site user, in order to not get overwhelmed with the amount of eligibility questions on a life event page, I would like my experience on BEARS to be customized based on my answers to a few top-level questions.

Pre-conditions:

- #261 is completed

Acceptance criteria:

- The user can provide answers to the top-level eligibility questions that are displayed at the top of the criteria section on each life event page: https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/screen/48053977-bc1b-4cea-978b-49fcb2dcc29a/
- Answers to top-level questions determine visibility of the follow-up questions (greyed out / inactive)
- Answers to top-level questions determine visibility of the ineligible benefits (greyed  out / inactive)

Definition of Done:
- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by fpigeonjr** [comment]
closing since this has been [merged into #262 ](https://github.com/GSA/usagov-benefits-eligibility/issues/262)
