### ISSUE TITLE
SPIKE: New Data Field (Location/Zip Code)

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#199]
As a BEARS site user, in order to get an accurate list of benefits which I might be eligible for based on my information, I would like to provide my location information for benefits that have location as one of the eligibility requirements (example: zip code).

Acceptance Criteria:

-  The user can input location information on the life event page under left-hand-rail filters
-  The provided information is validated against eligibility requirements

Location info considerations:

- provided zip code matches a predefined list/range of zip codes
- provided city, state is within predefined area
- disaster zones are dynamic and are regularly updated

Examples: 

- [DissasterAssistance.gov](https://www.disasterassistance.gov/get-assistance/address-lookup)
- [FEMA](https://www.fema.gov/disaster/current#current-disaster)

Resources:

- [OpenFEMA](https://www.fema.gov/about/reports-and-data/openfema)
- [FEMA Web Declaration Areas](https://www.fema.gov/openfema-data-page/fema-web-declaration-areas-v1)

Definition of Done:
- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by lgarceau768** [comment]
Couple Questions @r-bartlett-gsa 
Are we only thinking about present disasters or does the time period matter. I.E.
    - If you lived in a state where Hurricane Katrina affected you but not longer live there do you qualify for? And for what?
 
Are benefit cards specific to a certain disaster or certain type of disaster? 

Does the type of disaster matter as well? I.E. OpenFEMA Api currently reports COVID-19 related disasters and if just being in a disaster zone is considered an acceptance criteria how would that interaction proceed?

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 
We should be looking at present disasters that have a future closeout date. The closeout date indicates a date after which the users can no longer apply for FEMA assistance.

The benefit cards will be specific to FEMA assistance, and not specific to any disaster.

The types of disaster that we should be looking at are Presidentially declared disasters which include major disaster and emergency disaster declarations. (I believe COVID-19 was a emergency declaration).

So when the user inputs a zip code on BEARS, the system should validate if that zip code is in a Presidentially declared disaster area and that disaster hasn't been closed out.

**Comment by lgarceau768** [comment]
@r-bartlett-gsa Would it make more sense to check for disasters using Disaster Declaration Summaries from the FEMA API, returns open disasters currently in VA (this is 1 of the 2 covid related disasters that we get back from the Fema API)
`{
            "disasterNumber": "9",
            "ihProgramDeclared": false,
            "iaProgramDeclared": true,
            "paProgramDeclared": true,
            "hmProgramDeclared": true,
            "state": "TX",
            "declarationDate": "1953-06-19T00:00:00.000Z",
            "fyDeclared": 1953,
            "disasterType": "DR",
            "incidentType": "Flood",
            "title": "FLOOD",
            "incidentBeginDate": "1953-06-19T00:00:00.000Z",
            "incidentEndDate": "1953-06-19T00:00:00.000Z",
            "disasterCloseOutDate": "1958-01-01T00:00:00.000Z",
            "declaredCountyArea": "",
            "placeCode": "",
            "hash": "fbad8c1c133e488d24ad7964b1661dc860594eff",
            "lastRefresh": "2021-07-13T23:01:14.056Z",
            "id": "60c3b7a8a0ee349d710252f0"
        },`

Or with using the link provided above to search for disasters that are documented here [FemaWebDeclarations](https://www.fema.gov/openfema-data-page/fema-web-declaration-areas-v1)

An example of a disaster from the above endpoint is as follows
`{   
      "disasterNumber": 1694,
      "programTypeCode": "PA",
      "programTypeDescription": "PA - Public Assistance",
      "stateCode": "NJ",
      "stateName": "New Jersey",
      "placeCode": "99041",
      "placeName": "Warren (County)",
      "designatedDate": "2007-05-16T00:00:00.000Z",
      "entryDate": "2007-05-16T00:00:00.000Z",
      "updateDate": "2007-05-16T00:00:00.000Z",
      "closeoutDate": "2017-08-02T00:00:00.000Z",
      "hash": "257f124d3cf55e09fe0d582d74f4ed82e5ebd88a",
      "lastRefresh": "2021-07-13T22:47:34.273Z",
      "id": "60c3b89aa0ee349d710c8d80"
    },`

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 I'm not sure which one would make more sense. By looking at the two comparisons, the second has more information for location (state and county), the closeout date and the program type. However, the first one has the program type (IH, IA, PA and HM), the disaster type, the closeout date but it does not have the county (but it's a disaster from the 50s, so it might be just outdated/inaccurate record). Perhaps we can chat about this, but I'm leaning towards the first one, the Disaster Declaration Summaries if there's enough to determine location based on entered zip.

**Comment by lgarceau768** [comment]
End up pausing on this spike, due to several reasons.
The current architecture of the criteria store has arisen some issue with the concept of linking certain benefit cards to certain types of disasters. Here is where I was faulting, our criteria store validates the benefit cards via a variable called the `criterion.response` value that is validated against the acceptance criteria to determine the users eligibility, but with having to make a web request in order to determine if the user's zip code is in a disaster zone, based on the logic of the validation it would require a different criteria key being used for each different use case of the location type, which is not a feasible option.
