### ISSUE TITLE
mobile/responsive styles

### ISSUE THREAD

**Issue by fpigeonjr** [GSA/usagov-benefits-eligibility#227]
As a BEARS site user, in order to browse benefits efficiently on multiple screen-sizes, I would like to have a great user experience on a mobile phone.

Acceptance criteria:

- [x] Fix navigation menu
- [x] Within benefit card, stack options vs 2 column layout

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [x] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [x] Usability testing
- [x] PR approved / Peer reviewed
- [x] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[Default Flexion DoD](https://docs.google.com/document/d/1UuefRq7qUjS_oOqPs8JwPxqVoouyyGiuPTL1kzQG2mY/edit)

**Comment by fpigeonjr** [comment]
🚀@GSA/bears Federalist [preview link](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/preview/gsa/usagov-benefits-eligibility/us/227/) for your review. Appreciate any feedback on mobile experience.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr It looks really nice!! Here's some minor feedback:

Current: On life event pages, Sort is displayed above filters. See https://www.screencast.com/t/MUIUdofq3
Suggested: Move sort below filters and above the results.

Current: On life event pages, Open All / Close All is missing.
Suggested: Show Open All / Close All below the filters and above the results (below sort?).

Current: On type and agency pages, Open All / Close All is breaking onto a second line. See https://www.screencast.com/t/EPskc1D3buY
Suggested: Display Open All / Close All on one line.

**Comment by maomeara63** [comment]
@fpigeonjr @r-bartlett-gsa It might be worth it to check the usability of the cards in mobile. The long, narrow copy for the eligibility criteria is not optimal for readability. I'm wondering about a different treatment -- maybe the filters followed by the cards, or a single column of eligibility criteria? Regardless, I'm worried about usability.

**Comment by r-bartlett-gsa** [comment]
@maomeara63 Eligibility criteria **is** displayed in a single column. Is that not what you are seeing?

And we definitely should test on mobile with users. Let's add that to our plan.

**Comment by maomeara63** [comment]
@r-bartlett-gsa I'm seeing two column. Maybe it is browser-dependent
![BEARS](https://user-images.githubusercontent.com/65717217/155392057-e600d04a-553b-4f18-9c8d-86cfa6e87230.JPG)
?

**Comment by r-bartlett-gsa** [comment]
@maomeara63 Yeah, I would be worried about usability of this too. Are you reviewing this link: https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/preview/gsa/usagov-benefits-eligibility/us/227/

It should look like this: https://www.screencast.com/t/KKXR7Kdz3qr

**Comment by maomeara63** [comment]
@r-bartlett-gsa That is the link I'm looking at. I'm not sure what is happening. When I resize to mobile it shows the filters and the results side-by-side and the eligibility criteria in two column. But when I look at using Developer Tools results show up under filters and criteria are in one column. Let's look at it tomorrow. It might be user error. (Me being the user.)

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Additional feedback per [slack conversation with Meghan](https://flexion.slack.com/archives/C01RH0MD6MC/p1646239643409539):
New open/close buttons on mobile should have appropriate styling to indicate the button state.

**Comment by fpigeonjr** [comment]
Got it @r-bartlett-gsa. Thanks @maomeara63 for your feedback.
Sounds like a want to blue background on active button state and white background for inactive state for open/close buttons.

<img width="472" alt="button states" src="https://user-images.githubusercontent.com/4629398/156577648-6ba10c23-7fc3-4678-94cc-71b13c41d61a.png">

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa and @maomeara63 the toggle-able open/close buttons have been added.
The changes have been merged in and can be seen live on the [main preview link](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/site/gsa/usagov-benefits-eligibility/).

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Can you please move the 'Clear my selections' above 'Sharing and Printing' section on mobile: https://www.screencast.com/t/FRfiywWL (Or do you think it should be part of [#160](https://github.com/GSA/usagov-benefits-eligibility/issues/160) feedback?)

**Comment by maomeara63** [comment]
@r-bartlett-gsa @fpigeonjr I wasn't at the code jam, but I wonder if users will associate clearing the criteria with the cards or the filters?

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa just merged in the changes we discussed this morning.

**Comment by fpigeonjr** [comment]
> @r-bartlett-gsa @fpigeonjr I wasn't at the code jam, but I wonder if users will associate clearing the criteria with the cards or the filters?

We talked it over and agreed to move the `Clear Selection` button in the Selection area, same location as desktop.

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa Ran the homepage and Life Event detail page thru cross-browser testing and we're looking good.
