### ISSUE TITLE
Document GitHub access process

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#233]
As a GitHub repository administrator, so that I can more easily / quickly support our development team, I would like additional documentation on how to grant access to our GitHub repository.

- [ ] How does a user gain access to GitHub?
- [ ] How does a user join the GSA organization?
- [ ] How does a user join the appropriate teams?
- [ ] How does a user gain the ability to update the repository (e.g., write permissions)?

**Comment by wesley-dean-gsa** [comment]
1. eQip has to be approved
2. user needs access to GSA email
3. user needs a GitHub.com account (self-service)
4. user needs to be added to GSA organization (Jona)
5. user needs to be added to @GSA/bears as well as GSA/bears-content or GSA/bears-engineers  (as appropriate)

**Comment by r-bartlett-gsa** [comment]
For item#3 above, https://content.govdelivery.com/attachments/USGSA/2020/07/30/file_attachments/1507873/GSA%20GitHub%20Reference_Final.pdf (see pages 3 and 4):

- add your GSA email to your GH profile
- add your (general) location
- add your company and/or agency (example: 10x team @ Flexion)
- turn on MFA

**Comment by wesley-dean-gsa** [comment]
@r-bartlett-gsa THANK YOU!!!

**Comment by jonadecker** [comment]
@wesley-dean-gsa after number 4 (either before current 5 or after):

request access to Federalist in TTS Slack (#federalist-support channel) and @ mention one or more non-contractor 10x PMO resources

**Comment by wesley-dean-gsa** [comment]
Revised list:

1. eQip has to be approved
2. user needs access to GSA email
3. user should get a GitHub.com account (self-service; optional)
4. user has their GSA email, general location, and company / agency (e.g., "10x team @ Flexion") added to their GitHub.com account
5. user has enabled Multi-Factor Authentication (MFA) on their GitHub.com account
6. user's GitHub.com account needs to be added to GSA organization (Jona)
7. user needs to be added to GSA/bears as well as GSA/bears-content or GSA/bears-engineers (as appropriate)
8. user should request access to Federalist in TTS Slack (#federalist-support-channel) and `@` mention on or more _non-contractor_ 10x PMO resources

**Comment by jonadecker** [comment]
Typo in number 8 @wesley-dean-gsa ... one or more. May be a rekeying issue.

**Comment by wesley-dean-gsa** [comment]
@jonadecker  Got it.  Thank you!
