### ISSUE TITLE
Benefit card does not stay open if a selection is made

### ISSUE THREAD

**Issue by fpigeonjr** [GSA/usagov-benefits-eligibility#240]
Current: after selecting a criteria within the benefit card, the card collapses and moves out of the viewing area.
Suggestion: after selecting a criteria within the benefit card, the card should remain open and auto scroll with the re-sort.

Steps to reproduce:
1. Open any Life Event Benefit
2. Open a Benefit Card
3. Select any criteria
4. Card will collapse and be sorted

Interesting note:

In local development this is not an issue on node16. Once you run the build via `npm run federalist:local` and `npm start` the issue reappears. Possible that something in the build process is making this bug?

Screen capture taken from [federalist main branch](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/site/gsa/usagov-benefits-eligibility/)

https://user-images.githubusercontent.com/4629398/155017033-278dd830-cfca-47bf-b334-36b7a18dec74.mov

Definition of Done:
- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by jschoenemann-cms** [comment]
I think this was fixed as part of a different issue.   I found a problem with the sorting working differently on the local setup vs static site that gets published to federalist.   Please retest once this PR gets merged in:
https://github.com/GSA/usagov-benefits-eligibility/pull/308
