### ISSUE TITLE
Remove USWDS library that's committed to the repository

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#260]
As an engineer, so that I'm using the pinned version of the USWDS library, I need to have the committed library removed from the codebase and have links to that library refactored.

https://github.com/GSA/usagov-benefits-eligibility/tree/main/static/assets/js

**Comment by wesley-dean-gsa** [comment]
The version we have in our repository has multiple vulnerabilities, one of which is a "high"

https://github.com/GSA/usagov-benefits-eligibility/security/code-scanning

**Comment by wesley-dean-gsa** [comment]
The documentation ([link](https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/)) uses `uswds-gulp` which isn't included in our project.  They also provide a `gulpfile.js` that may be used to do the thing.

For reference, here's our stuff ([link](https://github.com/GSA/usagov-benefits-eligibility/blob/main/gulpfile.js#L10-L12)) that relates to the USWDS JavaScript code: 

```javascript
gulp
    .src('node_modules/uswds/dist/js/**/*')
    .pipe(gulp.dest('./assets/js/'));
```

Per "step 6" in the documentation, we may need to add a command to run `npx gulp build-sass` when the project's CSS is (re-)compiled.

**Comment by fpigeonjr** [comment]
We can consider using the [uswds/compile](https://github.com/uswds/uswds-compile) tool from the uswds team.
