### ISSUE TITLE
SPIKE: High-value eligibility questions

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#261]
As a BEARS site user, in order to not get overwhelmed with the amount of eligibility questions on a life event page, I would like to first answer only a few high level questions that would customize their further experience on BEARS.

SPIKE: Brainstorm as a team on design and functionality options. Some of the consideration / questions to answer before moving to #167 and #262:

**Frontend**
- Where and how high-value questions are displayed?
- Should answers to high-value questions eliminate unnecessary questions or reveal relevant questions?
- Should answers to high-value questions eliminate non-eligible benefits, or should those non-eligible benefits be labeled differently?

 **Backend**
- How do we allow content managers to control high-value questions? Via life-event.md?
- Each life event might have different high-value questions with different follow-up questions.

**Use cases**
- Date question and duplicate benefits: Currently the default state is to display all the benefits and the benefits are resorted based on filters (they are not eliminated). Some benefits are duplicate to account for the different eligibility criteria based on applicant's age.  Example: Social Security Disability Insurance for Child (Disability life event) or Survivor Benefits for Child (Death and Burial life event).
- True/false question and criteria groups: Some requirement question groups might be irrelevant to some users and might present unnecessary complexity/noise to the filters section. For example military status on the Death and Burial life event, or losing a family member on Disability life event.

**Comment by fpigeonjr** [comment]
[First pass](https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/) at frontend take for top-level aka high-value eligibility questions.

**Comment by r-bartlett-gsa** [comment]
Thank you @fpigeonjr! I like this version the best: 
![image](https://user-images.githubusercontent.com/66442872/157729003-9fe72eb5-9bcd-4f8e-9020-1c956bdd812c.png)

**Comment by fpigeonjr** [comment]
Thanks for your feedback @r-bartlett-gsa.

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa I've updated [option 3](https://xd.adobe.com/view/31961c00-7a06-4e00-82a9-d9f774115d0c-64c5/screen/48053977-bc1b-4cea-978b-49fcb2dcc29a) based on the feedback from standup.
