### ISSUE TITLE
Rollback interactive benefit card feature

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#268]
As a BEARS user, in order to successfully and efficiently find the benefits I might be eligible for, I would like life event pages to be clear and intuitive and I am not confused or overwhelmed with the amount of interactive options.

Acceptance criteria:

- The user can no longer interact with the eligibility criteria within the benefit cards (in-card interactive feature is rolled back)
- All eligibility criteria assigned to the benefit is presented to the user (the criteria label and acceptable values (for select fields) are displayed, as it was before in-card interactive feature was implemented)
  - Acceptable values for the radio fields are not displayed in the benefit card
- As the user interacts with the criteria on the left pane, the matching criteria is identified accordingly (green, red or no-change)
- The previous circle icons are replaced with checks or X icons (so the user is not tempted to click in the circle icon, as it was before)

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [ ] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by r-bartlett-gsa** [comment]
Old notes:

- Radio button criteria font and weight vs radio button options
- Negative selections statements are confusing
- 'not applicable' radio button selection should change the criteria font color (to red) and weight as that is an unmet criteria, see https://github.com/GSA/usagov-benefits-eligibility/issues/157 feedback
- Should we revert the interactive card feature due to usability challenges? Instead of round icons just show checks, so there's no visual confusing that something is clickable.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Moving this back to Doing column because the last acceptance criteria is not completed. Let me know if you would like to meet and discuss possible options.

**Comment by fpigeonjr** [comment]
ok @r-bartlett-gsa, this one is ready for review. Thanks for your feedback.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Looks great! PO approved.
