### ISSUE TITLE
ATO for bereavement life event

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#280]
As a BEARS stakeholder, in order to prepare for the bereavement life event launch, I would like BEARS application to go through Federalist security authorization process and acquire an ATO decision.

Preconditions:

- USAGov (Russell) initiates the conversation with the Federalist team
- Request is submitted for subdomain: benefits-tool-beta.usa.gov

Acceptance Criteria:
TBD

Tasks:

- Subdomain
- [Federalist site info form](https://docs.google.com/forms/d/e/1FAIpQLSfprbZ7IJLw7v1i7mNG-Av88kiBBSl88uQ49Ijv9TqW9URvQw/viewform)
- System description - no need with federalist
- FIPS 199 data categorization

**Comment by wesley-dean-gsa** [comment]
I sent the following message to Russell today (Tuesday, March 8th) at 11:59am Eastern:

> Hey Russell, thank you for your perspective in the BEARS call yesterday (Monday, March 7th).  We've continued the conversation on our side, specifically with regards to the ATO process and how it may be affected by a stand-alone Federalist site vs pushing stuff into a Drupal instance.
> 
> Long story short, we were thinking about reaching out to [#federalist-support](https://gsa-tts.slack.com/archives/C1NUUGTT5) (and maybe tagging [@lindsay (she)](https://gsa-tts.slack.com/team/W015E5GF5CY) since she [recently responded](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1643033775000900) to someone else's similar question) , sharing our [repo](https://github.com/GSA/usagov-benefits-eligibility), making them aware that we're interested in making a preview site public-facing (per our conversation yesterday), and otherwise getting on their radar.  [@Jona Decker (10x, MSN, she/her)](https://gsa-tts.slack.com/team/U01JEQDSQ3W) pointed out that it may be best if that conversation were to be started from a fed instead of a contractor (such as myself).
> 
> So, question is, do you have any thoughts, concerns, reservations, recommendations, etc. for how to move forward with this?
