### ISSUE TITLE
Header and Footer Revisions

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#306]
As a BEARS site user, in order to have a seamless navigation from USAGov to BEARS and from BEARS back to USAGov, I would like BEARS one-life-event version's header and footer to match USAGov's as close as possible.

Acceptance Criteria:

- BEARS one-life-event version's header and footer are updated to match USAGov's header and footer

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [x] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by fpigeonjr** [comment]
Hi team, here is the [preview link](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/preview/gsa/usagov-benefits-eligibility/feature/usagov-header-footer/) for the USAGov header/footer feature.
As I mentioned at standup, we’ll need to integrate into the [single-life-event feature flag](https://github.com/GSA/usagov-benefits-eligibility/issues/307).

**Comment by fpigeonjr** [comment]
cross-browser testing looks good
