### ISSUE TITLE
Fix code scanning alert - High severity - Command Injection vulnerability in lodash.template

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#317]
Tracking issue for:
- [ ] https://github.com/GSA/usagov-benefits-eligibility/security/code-scanning/7

**Comment by lgarceau768** [comment]
Dismissed the issue as of right now due to this just being a static served site there is no danger in this vulnerability. There is also no easy fix to tis due to the fact that this is a nested dependency of the framework `nuxt` we are using.

**Comment by lgarceau768** [comment]
https://github.com/GSA/usagov-benefits-eligibility/security/code-scanning/7
Dismissed the issue, but for a fix I would go along the route of removing the uid's that the package is creating as well as the function chaining and data manipulation of the benefit cards
