### ISSUE TITLE
Increase code test coverage

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#358]
# User Story

As a BEARS **developer**, in order to **ensure our code is rigorously tested**, I would like **additional unit tests coverage** .

Pre-conditions:

- [ ] current code coverage report shows 83.7% coverage

![bears-coverage-2022033001](https://user-images.githubusercontent.com/87149725/160865623-e7d6bb22-ef06-4034-a941-7b955ac54189.png)

Acceptance Criteria:

- [x] code coverage report shows 90% or more coverage, per the TTS QASP

Definition of Done:

- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Build process and deployment is automated and repeatable
- [ ] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved

**Comment by wesley-dean-gsa** [comment]
duplicates #379

**Comment by wesley-dean-gsa** [comment]
resolves #379

**Comment by lgarceau768** [comment]
Code coverage is being shown as 92.7% in SonarQube!
