### ISSUE TITLE
Add //NOSONAR annotations

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#373]
# User Story

As a BEARS **security engineer**, in order to **avoid false-positive SonarQube security findings**, I would like **annotations added to our code to instruct SonarQube from raising known false-positives** .

Pre-conditions:

- [ ] in ticket #345 there were four findings that were mitigated but still resulting in (false-positive) findings on two lines

Acceptance Criteria:

- `//NOSONAR` added to the following lines:
  - [ ] [components/Accordion.vue:51](https://github.com/GSA/usagov-benefits-eligibility/blob/main/components/Accordion.vue#L51)
  - [ ] [components/Accordion.vue:75](https://github.com/GSA/usagov-benefits-eligibility/blob/main/components/Accordion.vue#L75)

Definition of Done:

- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed (e.g., SonarQube)
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Build process and deployment is automated and repeatable
- [ ] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved

**Comment by wesley-dean-gsa** [comment]
https://stackoverflow.com/questions/58682506/how-can-i-mark-this-line-in-html-file-to-be-ignored-by-sonar-rules

HTML scanner's test code:

```HTML
    List<Node> nodeList = new PageLexer().parse(new StringReader("<table>\n<!-- //NOSONAR --><td>\n</table>"));
```

**Comment by wesley-dean-gsa** [comment]
another example of `//NOSONAR` with HTML:

```HTML
<template data-sly-template.step>
    <!-- //NOSONAR --><li
        data-sly-use.localStep="MyAdapter"
        data-sly-test="${(wcmmode.edit && localStep.start) || !wcmmode.edit}"
```

**Comment by wesley-dean-gsa** [comment]
I don't see where this has been merged into the main branch.  When I go to the two links listed in the "Acceptance Criteria" section of this ticket, the annotations aren't there.  There are no comments referencing PRs, nor are there any links to PRs.  They may exist -- I hope they do -- but I'm not finding it.

I'm inclined to believe that a branch was cut and the work was done, I just can't find it.

Once the `//NOSONAR` annotations are added, the security hotspots mentioned in #345 ought to go away.

**Comment by lgarceau768** [comment]
I was unable to get the `<!-- //NOSONAR -->` comment to be recognized within my Sonarqube instance. Since the risk has been mitigated with the `sanitizeBenefitUrl` method to handle bypassing the built in vue sanitzation. Will be closed since this is probably an issue of the linter moving it or it not being able to ignore the inline html attribute injected javascript.
