### ISSUE TITLE
Update test code

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#379]
# User Story

As a BEARS **engineer**, in order to **improve our test code coverage (specifically) and produce better code (in general)**, I would like **to have our test code updated** .

Pre-conditions:

- [x] current test code coverage is at 84% (entire project) / 88% (code since March 29th)
- [x] project requirement is 90% test code coverage

Acceptance Criteria:

- [x] code coverage meets or exceeds 90%

As of Monday, April 11th, an LCOV report run on the entire BEARS repository shows that almost half (35 of 72) lines of uncovered code are in `components/dateHelper.js`; therefore, updating our test code coverage for this file alone would push us over the 90% test code coverage threshold.  The file with the second most uncovered lines is `services/stringToHash.js` with 14 lines.

Here are the report I just ran:

dateHelper.js: [bears-uncovered-2022041101.pdf](https://github.com/GSA/usagov-benefits-eligibility/files/8465765/bears-uncovered-2022041101.pdf)
stringToHash.js: [bears-uncovered-2022041102.pdf](https://github.com/GSA/usagov-benefits-eligibility/files/8465853/bears-uncovered-2022041102.pdf)

Updating test code for those two files would bring us to roughly 95% coverage would is AMAZING.

Definition of Done:

- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Build process and deployment is automated and repeatable
- [ ] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved

**Comment by wesley-dean-gsa** [comment]
this is closely related to #358

**Comment by wesley-dean-gsa** [comment]
resolves #358

**Comment by lgarceau768** [comment]
Coverage is currently reported as 92.7% in my SonarQube!
