### ISSUE TITLE
Accessibility issue with screenreader

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#397]
See item 5 in #337  
This is a USWDS bug.

**Comment by fpigeonjr** [comment]
Dug into this a bit and this is what the uswds team [reported](https://github.com/uswds/uswds/issues/4630#issuecomment-1197057514). The issue has been closed since they could not duplicate the issue and the code/content has changed since when we submitted this issue.

> I ran through each accordion without that reported error. I tested on my PC in Chrome with NVDA. I did notice that the video of the error in GitHub looks different than the website provided. Has the website been updated or is it possibly a different link? The other thing I noticed was that the screen reader would state “graphic you did not provide information for” on each bullet within the accordion. I am not sure if this is intended behavior but figured I would flag it.

**Comment by fpigeonjr** [comment]
Ran thru the accordions again in a Windows VM using Chrome/Firefox and NVDA. The accordions open/collapse as expected and am able to navigate the content using the down arrow key. Content does not repeat as it did before nor does it read the content once the accordion is opened.

May be good to run thru this again with @maomeara63 as a sanity check.

**Comment by fpigeonjr** [comment]
But, natively tabbing will not read the content inside of anything unless there is a link or some interactive element inside the accordion content.

Using VO, `ctrl-opt-super+p` will read the content inside the accordion an item at a time.

**Comment by fpigeonjr** [comment]
reviewed this with @maomeara63 and the accordions are announcing open/close and reading content as expected.
- tested on windows chrome/firefox and NVDA
- tested on VO on mac/safari/chromium
