### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#419]
**See section 6 in [Mural](https://app.mural.co/t/gsa6/m/gsa6/1651676481362/9b4042f21b4e4f37f08ba38ddceeef2e8b9bfa6e?sender=mariamarrero8185) for proposed feedback and color codes**

- [x] Update titles to title case instead of sentence case (content update, see [design-feedback-content](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/preview/gsa/usagov-benefits-eligibility/design-feedback-content/death-of-a-loved-one/?) branch)
- [x] Change "< Benefits, Grants, Loans" link font to bold
- [x] Change process list icon color and font color
  - [x] Move the disclaimer copy under item 2 in the process list
- [x] Add left and right section headers: "Answer a Few Questions" and "Federal Benefits Results"
- [x] Increase spacing between left and right sections
- [x] Move information microcopy outside and above left side section and top-align with right side controls
  - [x] Update the "!" icon
- [x] Change the top-level questions background and increase the background width
  - [x] Change the top-level questions font color
- [x] Indent the criteria questions under each section 
- [x] Change the question section headers font to Merriweather
- [x] Benefit cards:
  - [x] Change the header background from grey to white
  - [x] Change the header font color to blue
- [x] Ensure all color codes are as provided in [Mural](https://app.mural.co/t/gsa6/m/gsa6/1651676481362/9b4042f21b4e4f37f08ba38ddceeef2e8b9bfa6e?sender=mariamarrero8185), section 6 
- [x] Ignore benefit results separation into two sections
- [ ] Update BEARS favicon to USAGov's favicon (see comment below)

**Definition of Done:**
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [ ] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by r-bartlett-gsa** [comment]
| <link rel="apple-touch-icon-precomposed" href="/images/USA_Fav_Icon152_default.png">
  | <link rel="icon" sizes="16x16" href="/images/USA_Fav_Icon16.ico">
  | <link rel="icon" sizes="32x32" href="/images/favicon.ico">
  | <link rel="icon" sizes="152x152" href="/images/USA_Fav_Icon152_default.png">

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa and @maomeara63 still need to add favicon but can be a11y tested.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Looks great! Here are a few things that need to be updated:

- Increase the width of the process list
- The helper text on the left needs to top-align with the controls on the right
- The criteria questions section need to top-align with the benefits accordions/cards
- The left side scroll bar needs to be aligned with the questions section (not with the header of the questions)
- The questions need to be indented a bit more
- The + sign in the accordion needs to be dark blue
- Some additional spacing is needed below the process list, and between the left and right sections

**Comment by fpigeonjr** [comment]
> @fpigeonjr Looks great! Here are a few things that need to be updated:
Thanks @r-bartlett-gsa I'll get started on these fixes. Thanks for the feedback.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Thank you, Frank! We can also check-in tomorrow morning after stand-up, as some of these things might seem a bit "nit-picky".

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Question, should we move the benefit type filter above the benefit results? With the recent changes, it looks out of place where it it now: https://www.screencast.com/t/MSjD1qeTe3

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa 2nd pass is ready to be reviewed. Thanks for your attention to detail.

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr It looks great! Thank you.

**Comment by fpigeonjr** [comment]
> This story is in testing, but just a reminder that favicon still needs to be updated.

Favicon has been added.
