### ISSUE TITLE
Return to top issue

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#436]
Use of the Return To Top button breaks the ability to track criteria parameters in the URL.

After using the Return To Top, weird stuff starts happening to the url. You can end up with invalid urls like this: /death-of-a-loved-one/#/?e782efd=1&77edd0d=yes/?e782efd=1&77edd0d=no/?10dfdb0=1

The result is that the url being captured for use in the Sharing section (copy and email) does not work (or if you copy the url or use native sharing function on a phone). When you use the url to load a page, no filter selections are "pre-loaded". After the page loads, the problem will persist. And "clear selections" does not reset the url.

**If this can't be fixed, it might be better to remove it.** 

It might be possible to recode the back to top using [scrolling](https://www.w3schools.com/howto/howto_js_scroll_to_top.asp) and then [set focus](https://www.geeksforgeeks.org/javascript-focus/) for a11y.

**Comment by fpigeonjr** [comment]
The skipnav link is also having a similar issue.
You can access it by hitting tab one time. 
It's supposed to go to the `#main` section but adds it incorrectly to the url like return to top.
<img width="611" alt="Screen Shot 2022-05-20 at 2 03 05 PM" src="https://user-images.githubusercontent.com/4629398/169595107-4cdfe317-c920-4368-8a5f-d03357e72023.png">
