### ISSUE TITLE
Translations Feedback

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#480]
The following labels are not provided in any of the files:

- Select (default dropdown label) - needs to be added to en.json file under lifeEvent section: "dropdownLabel": "Select"
- Sharing and printing - needs to be added to en.json file under shareResults section: "header": "Sharing and printing"
- Clear my selections - needs to be added to en.json file under lifeEvent section: "buttonLabel4": "Clear my selections"

Alignment issue:

- The left pane and the the benefit results are not top-aligned: https://www.screencast.com/t/xIMSIWg4 - The sections need to remain aligned when the left information content length is updated.

**Comment by r-bartlett-gsa** [comment]
Select => Seleccione
Sharing and printing => Compartir e imprimir

**Comment by fpigeonjr** [comment]
Also noticed our filter area is not translated. Will fix as well.

<img width="950" alt="filters not Spanish" src="https://user-images.githubusercontent.com/4629398/175094479-8fbd9862-8aff-4f52-a092-c5bab0d40771.png">

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr That's correct, they are not translated because those fields were not added to en.json files when we exported them for translations. They have been added since then to lifeEvent section of that file. So no need fixing it :)
