### ISSUE TITLE
Translation fixes

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#495]
- [x] Frank: Add a label for print button to en/es json files
- [x] ~~Frank: Left and right section auto-alignment~~
- [x] Manually align left and right sections
- [x] Renata: Translation compare and QA + USAGov editing

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr It appears that the left pane and right sections are not auto-aligning horizontally in cases when the content length is updated. https://www.screencast.com/t/pzrxqD2s

Can you please update so the two sections auto-align despite the changing content length.

This is the branch I used: https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/preview/gsa/usagov-benefits-eligibility/translation-fixes/es/death-of-a-loved-one/?

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa: Left-right auto-alignment will be fixed in [PR500](https://github.com/GSA/usagov-benefits-eligibility/pull/500)

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr As we discussed let's revert the auto-alignment, so it does not affect the usability for keyboard users.

**Comment by fpigeonjr** [comment]
Thanks @r-bartlett-gsa, will do.
