### ISSUE TITLE
Relevancy Sorting is Inaccurate

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#510]
Relevancy sorting should be calculated by the percentage of the matched criteria. That's how it was setup and that is not the case currently.
Secondary sorting is alphabetical, and that is also not correct currently.

This is a high priority issue, as the benefits relevancy accuracy is key.

Examples: 

- Lump Sum Benefit should be above Survivor Benefit based on alphabetical order, because they tie in relevancy: https://www.screencast.com/t/7Zu8mIYlf
- Survivor Benefit for Mother/Father should be at the top, because criteria is matched 100%: https://www.screencast.com/t/z5FptxaZb
- Covid Assistance (60% match) should be higher than Veteran's Life Insurance (33%match): https://www.screencast.com/t/y7gsk2U3LgCf

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [x] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [x] Usability testing
- [x] PR approved / Peer reviewed
- [x] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Would you be able to do one last cross-browser testing as part of this DoD? If I remember correctly, you have access to the right tools.

**Comment by fpigeonjr** [comment]
👍 yes @r-bartlett-gsa, I can run the app through cross-browser testing.
