### ISSUE TITLE
Accessibility Issue, Row 95

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#515]
- [x] Row 95: When user selects Open All and Close All. buttons, screed reader announces the information which is not visible on the page. The status is not announced. Same issue is presented for the accordions. The open or close status is not announced. Retesting 7/5/22: The collapsed status is still not announced for the accordions.

**Comment by fpigeonjr** [comment]
reviewed this with @maomeara63 and the accordions are announcing open/close as expected.
- tested on windows chrome/firefox and NVDA
- tested on VO on mac/safari/chromium
