### ISSUE TITLE
Setup demo site

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#532]
As a benefit tool developer and content manager, in order efficiently implement and test new features, code updates and content updates, I would like to be able to preview the changes on the demo site before releasing them to production.

Acceptance criteria:

- [x] Benefit tool demo site is available and integrated part of the code release process

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [x] Accessibility tested
- [x] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [x] Usability testing
- [x] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by r-bartlett-gsa** [comment]
<img width="944" alt="Screen Shot 2022-08-09 at 4 04 37 PM" src="https://user-images.githubusercontent.com/66442872/183959603-600e9b8e-8d3b-46a9-85e7-4d86e5087eea.png">

**Comment by wesley-dean-gsa** [comment]
[documentation](https://cloud.gov/pages/documentation/#basic-settings)

we need to decide what URL the demo site should live at (e.g., [benefits-tool-beta-demo.usa.gov](http://benefits-tool-beta-demo.usa.gov/) or whatever)

**Comment by r-bartlett-gsa** [comment]
I'm cool with `benefits-tool-beta-demo.usa.gov`

@erniedeeb Are you ok with this URL for staging?

**Comment by erniedeeb** [comment]
LGTM

**Comment by wesley-dean-gsa** [comment]
Awesome.  Thanks, @r-bartlett-gsa and @erniedeeb !!

**Comment by wesley-dean-gsa** [comment]
Russell sent along the following information on Thursday, December 22nd:

> RE: STASK3312671 - RITM1032553 - DNS.Both Internal and External.New Domain
> 
> > Good afternoon.  I am emailing about a DNS ticket that was opened for:
> >
> > Please add the following DNS records for [benefits-tool-beta-demo.usa.gov](http://benefits-tool-beta-demo.usa.gov/)  and _[acme-challenge.benefits-tool-beta-demo.usa.gov](http://acme-challenge.benefits-tool-beta-demo.usa.gov/):
> > [benefits-tool-beta-demo.usa.gov](http://benefits-tool-beta-demo.usa.gov/) CNAME to [benefits-tool-beta-demo.usa.gov.external-domains-production.cloud.gov](http://benefits-tool-beta-demo.usa.gov.external-domains-production.cloud.gov/)
> > _[acme-challenge.benefits-tool-beta-demo.usa.gov](http://acme-challenge.benefits-tool-beta-demo.usa.gov/) CNAME to _[acme-challenge.benefits-tool-beta-demo.usa.gov.external-domains-production.cloud.gov](http://acme-challenge.benefits-tool-beta-demo.usa.gov.external-domains-production.cloud.gov/)
> > 
> 
> These 2 records have been created as requested.  Please let me know if you have any questions or concerns.

**Comment by wesley-dean-gsa** [comment]
I recommend not moving forward with the additional configuration changes needed to advance this ticket until after the New Year when Pages folks are around for support.

**Comment by wesley-dean-gsa** [comment]
On Tuesday, January 4th, Russell wrote:

> Catching up on things from being on leave and just wanted to follow up on this to see if y'all were able to successfully set up the staging domain.  I have to get back to the GSA IT security team so that they can validate the domain for BOD 18-01 compliance (just making sure it's only accessible through HTTPS, basically).

..to which I (Wes Dean) responded:

> I'm back from leave today (Monday, January 16th) but I have yet to address the demo / staging project.  I intend to focus on it this week.

**Comment by wesley-dean-gsa** [comment]
Yesterday (Tuesday, January 24th), Andrew Burnes provided a [link to a form](https://docs.google.com/forms/d/1ujDu9mUNmHuCG2Mx5JYFUaXthYrf304yMpBrGOEudMA/edit) that needs to be completed before the Pages team can proceed.  @FatmaBakir and I completed the form and submitted it later that day.

Andrew told us that it would take roughly a week before the work would be completed.  Also, he mentioned that a security scan will need to be passed before they'll make the site live.

When we took the BEARS site live last year (2022), their team ran a Sonarqube scan against our repository.  Their scan was largely fine.  They had some questions which we (Russell O'Neill and I) were able to satisfy.

A Sonarqube scan reports that there were several security hotspots, all of which related to the fact that we're using our own function, [sanitizeUrl](https://github.com/GSA/usagov-benefits-eligibility/blob/main/mixins/SanitizeBears.js#L5) to sanitize URLs instead of using Vue's built-in method.

**Comment by wesley-dean-gsa** [comment]
Tangentially, Vue's [documentation](https://vuejs.org/guide/best-practices/security.html#potential-dangers) references the URL sanitization library that we're using:

> There's a potential security issue if the URL has not been "sanitized" to prevent JavaScript execution using javascript:. There are libraries such as [sanitize-url](https://www.npmjs.com/package/@braintree/sanitize-url) to help with this [...]
