### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#534]
As a benefit tool developer or content manager, in order to effectively and safely release site changes, I would like an updated release workflow as follows:

- folks continue using branches to do their work (no change)
- folks create PRs that are reviewed by other people (no change)
- upon approval, PRs update the main branch (no change)
- the main branch is reflected in a demo / preview / staging site with a constant URL, but not the live site (this is a change!)
- to update the live site, someone creates a [release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases); this release is, essentially, a point-in-time copy of the main branch (so, additional updates to main don't update the live site until someone creates another release)

Acceptance criteria:

- [ ] The code release process is updated so code changes are pushed through PR process to demo site, and then through release process to live site

Definition of Done:
- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by wesley-dean-gsa** [comment]
Background: this came from a conversation we had with some folks on the team about having a "demo URL" or "staging URL" where folks could see merged changes in one place prior to making the changes are published to the live / prod site.

The release-related stuff takes advantage of some GitHub functionality that's related to this kind of workflow; however, it's possible to implement this without using GitHub releases (e.g., tagging).

One notable change related to this workflow is the establishment of the demo / staging URL.  This would involve setting up a URL or subdomain that remains constant (i.e., it doesn't change, it's not named for a specific branch, etc.) that would be _in addition to_ the live URL.

So...

* developer pushes commits to a branch: variable [(preview) URL](https://federalist.18f.gov/documentation/previews/) at Federalist that's tied to that specific branch
* team merges a branch into main: constant URL hosted on Federalist that's tied to the repo's `main` branch
* team publishes a release: constant URL hosted on Federalist that displays the latest release (or a `release` branch)
