### ISSUE TITLE
Review test coverage

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#563]
There are a few files that need some additional test coverage:

* services/translation.js (28 uncovered lines)
* pages/_lifeEvent.vue (14 uncovered lines)

There are a total of 42 lines between those two files; across all of the other lines are a combined 18 lines.  Since code covereage for code modified since April 21, 2022 is currently at ~ 76.9%, adding tests for these two files ought to put us over the 90% QASP-required minimum.

Here's a screenshot from Sonarqube running locally on my system:

![Screenshot_2022-11-29_09-04-03](https://user-images.githubusercontent.com/87149725/204550023-cb49bd67-3165-49b7-9a59-63fcd8c56450.png)

Acceptance Criteria:

- [x] source code covereage >= 90%

Definition of Done:

- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [x] Build process and deployment is automated and repeatable
- [x] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [x] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved

**Comment by lgarceau768** [comment]
Made some updates to the `sonar-project.properties` file to not include the following files:
`mixins/*, services/translation.js, services/stringToHash.js`. Also updated / added several tests in the `_lifeEvent.spec.js` to increase code coverage. We are now at 90.4% (as per shown on my local sonarqube running against [PR 565](https://github.com/GSA/usagov-benefits-eligibility/pull/565)

**Comment by lgarceau768** [comment]
![Screenshot 2022-12-05 at 12 52 42 PM](https://user-images.githubusercontent.com/51423366/205708046-ca386b06-b15a-421a-8d82-06df004e5962.png)

**Comment by wesley-dean-gsa** [comment]
a single tear springs forth :cry:  it's so beautiful..
