### ISSUE TITLE
Cross-referenced life event links break after page reload

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#578]
Cross-referenced life event links don't work properly after page reload. To replicate:

- From Death of a loved one life event, click on Retirement life event card at the bottom of the page
- On Retirement life event, reload the page and click on Death of a loved one life event card

See: https://www.screencast.com/t/tnYGvS8WDl0r

**Comment by fpigeonjr** [comment]
Thanks for providing the screencast @r-bartlett-gsa. This will be helpful in recreating the bug.
