### ISSUE TITLE
Landing page for multiple life events

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#579]
As a benefits tool user, in order to navigate between USAGov and benefits tool subsite without confusion, I would like the benefit tool subsite to resemble USAGov as close as possible and life experiences to be seamlessly integrated to appropriate USAGov content.

Note: currently when multiple life experiences are turned on, BEARS nav displays instead of USAGov nav and a landing page exist with links to all life experiences.

Acceptance Criteria:

- When multiple life experiences are enabled: 
  - [x] the users are not able to navigate to BEARS legacy landing page 
  - [ ] the header, main nav and footer are the same as on a single-life experience (replicated USAGov's header, main nav and footer; additional header, main nav and footer changes are described in separate user stories: #580, #581, #582)

Definition of Done:
- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa @erniedeeb:
Was thinking about this today and was wondering what should we do if the user naviagtes to the root of the site?
Maybe we just redirect to the `death-of-a-loved-one` life event like we do in the in the single life event version?

also tangentially-related, do we want to remove the pages for `benefits by type` and `benefits by agency` since it sounds like the user will never see these?

<img width="537" alt="SCR-20230117-cmn" src="https://user-images.githubusercontent.com/4629398/212935464-5b9d9a7d-cdc9-46f1-9f33-894f93aa5a3a.png">

**Comment by r-bartlett-gsa** [comment]
Great questions @fpigeonjr! I'm thinking that all (root/benefits by life event, benefits by type and benefits by agency) should redirect to either https://beta.usa.gov/benefits or https://www.usa.gov/benefits. Considering that we are preparing to launch additional life events, it does not seem correct to redirect all to a single bereavement life event. Also, this is assuming that the benefit page page on USAGov will have appropriate links to BEARS life events.

What are your thoughts @erniedeeb?

**Comment by fpigeonjr** [comment]
maybe something like this?
<img width="1782" alt="SCR-20230117-dj4" src="https://user-images.githubusercontent.com/4629398/212944023-5d255407-13a9-4125-9dd0-486428775a8a.png">

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr I'm not sure if I fully understand the diagram above (or agree with it). I was thinking that:
benefit-tool-beta.usa.gov redirects to usa.gov/benefits
benefit-tool-beta.usa.gov/types redirects to usa.gov/benefits
benefit-tool-beta.usa.gov/agencies redirects to usa.gov/benefits
benefit-tool-beta.usa.gov/becoming-a-parent redirects to usa.gov/benefits
benefit-tool-beta.usa.gov/financial-hardship redirects to usa.gov/benefits
benefit-tool-beta.usa.gov/military-service redirects to usa.gov/benefits
benefit-tool-beta.usa.gov/national-emergency-and-disaster redirects to usa.gov/benefits
benefit-tool-beta.usa.gov/school-and-education redirects to usa.gov/benefits
**benefit-tool-beta.usa.gov/death-of-a-loved-one does not redirect
benefit-tool-beta.usa.gov/retirement does not redirect
benefit-tool-beta.usa.gov/disability does not redirect**

**Comment by fpigeonjr** [comment]
updated the diagram to make it a little easier to understand.
<img width="2140" alt="SCR-20230117-ezj" src="https://user-images.githubusercontent.com/4629398/212960975-edacf7aa-deb8-4627-97d4-de478cd7a68d.png">

**Comment by erniedeeb** [comment]
Good convo here. I'd want the redirect to beta pages instead of the old usa.gov. So either [https://www.beta.usa.gov/benefits](https://www.beta.usa.gov/benefits) or [https://www.beta.usa.gov/life-experiences](https://www.beta.usa.gov/life-experiences) should work. I like the latter because it gets people thinking about life events, but the former is more broad and might be more helpful. A concern with the former though is that benefits.gov is front and center, which may end up pulling people away from benefits locator. What do you think @r-bartlett-gsa?

**Comment by r-bartlett-gsa** [comment]
@erniedeeb 
I'm leaning more towards [life-experiences page on beta.usa.gov/life-experiences](https://beta.usa.gov/life-experiences), it would be more in line with BEARS approach, however the life experiences don't exactly match up. As it is today, the user will not be able to get to disability benefits from https://beta.usa.gov/life-experiences We don't want to introduce additional barriers for the users to get to the information they need. As BEARS additional life experiences are released, will usa.gov update this page?

**Comment by danny-englander** [comment]
We'd like our UX person, Ernesto, who just came on to the project to give this a full review.

**Comment by fpigeonjr** [comment]
I have completed my involvement with this GitHub issue and am stepping away from it. 
Thank you for your understanding.
