### ISSUE TITLE
Header updates

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#580]
As a benefits tool user, in order to navigate between USAGov and benefits tool subsite without confusion, I would like the benefit tool subsite to resemble USAGov look and feel as close as possible.

Acceptance criteria:

- [x] Move the language toggle above the search bar
- [x] Update phone number in the header styling and placement to match USAGov's beta site

Resources: 

- [Design review document](https://docs.google.com/document/d/1mssKCrkDqNA4GrD-FO22pK5ZifI43hXw88Z8AYvdO4I/edit?usp=sharing) (#553)
- [Design prioritization spreadsheet](https://docs.google.com/spreadsheets/d/1JxpXDun8nagwVuYwc5a1PSZCPaGzhGcyJvIIYgX396s/edit?usp=sharing)

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [x] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by fpigeonjr** [comment]
This work is part of #616.

**Comment by danny-englander** [comment]
This is dependent on #582 and #581.

**Comment by fpigeonjr** [comment]
I have completed my involvement with this GitHub issue and am stepping away from it.
Thank you for your understanding.

**Comment by danny-englander** [comment]
@nehemiah-abuga This is ready for testing. For this ticket, we are testing the header for widescreens for visual similarity to https://beta.usa.gov/

1. Pull this branch locally: `multi-life-event-2023`
2. Test the header as compared to https://beta.usa.gov/ for desktop
3. switch languages to Spanish and repeat the test. 

Note, there may be some minor differences. _We will test for mobile_ once https://github.com/GSA/usagov-benefits-eligibility/issues/689 is complete, at the moment that ticket is blocked.

<img width="1024" alt="2023-03-28_15-12-41" src="https://user-images.githubusercontent.com/609623/228343261-a262009a-7ef5-4174-a9ae-c60c3e9f276b.png">

<img width="998" alt="2023-03-28_15-16-33" src="https://user-images.githubusercontent.com/609623/228344122-4b2d976c-cc33-4a49-9a04-952b92d9c781.png">

**Comment by nehemiah-abuga** [comment]
I have verified this change and the headers are similar.

**Comment by danny-englander** [comment]
Noting that Amy is testing the header over in https://github.com/GSA/usagov-benefits-eligibility/issues/581#issuecomment-1481902673 so I will mark this one as done.
