### ISSUE TITLE
Footer updates

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#582]
As a benefits tool user, in order to navigate between USAGov and benefits tool subsite without confusion, I would like the benefit tool subsite to resemble USAGov look and feel as close as possible.

Acceptance criteria:

- [ ] Update footer to match USAGov's beta site
- [ ] Update footer social media icons to match USAGov's beta site

Resources:

- [Design review document](https://docs.google.com/document/d/1mssKCrkDqNA4GrD-FO22pK5ZifI43hXw88Z8AYvdO4I/edit?usp=sharing) (https://github.com/GSA/usagov-benefits-eligibility/issues/553)
- [Design prioritization spreadsheet](https://docs.google.com/spreadsheets/d/1JxpXDun8nagwVuYwc5a1PSZCPaGzhGcyJvIIYgX396s/edit?usp=sharing)

Definition of Done:
- [x] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by danny-englander** [comment]
This is dependent on #580 and #581.

**Comment by fpigeonjr** [comment]
I have completed my involvement with this GitHub issue and am stepping away from it. 
Thank you for your understanding.

**Comment by danny-englander** [comment]
@nehemiah-abuga Ready for testing. 

- [ ] Pull `multi-life-event-2023` to your local
- [ ] run `npm i`
- [ ] Run `npm run dev`
- [ ] Go to http://localhost:3000
- [ ] Inspect the footer navigation and ensure that the link text and links match what is on https://beta.usa.gov/
- [ ] Switch language to Spanish
- [ ] Inspect the footer navigation and ensure that the link text and links match what is on https://beta.usa.gov/es
- [ ] Cross browser test this as well

**Comment by nehemiah-abuga** [comment]
I have validated the footer navigation and ensured the link text and links match

**Comment by danny-englander** [comment]
@amycole501 Ready for you to test. 

Steps

1. Go to: https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/?
2. test the footer navigation for accessibility 
<img width="1060" alt="2023-03-23_09-53-27" src="https://user-images.githubusercontent.com/609623/227225597-2c184ee7-fb60-4838-bf54-522560d3f202.png">

**Comment by amycole501** [comment]
1. Keyboard interaction was fine (Chrome, desktop).
2.  The footer header levels are set to H2. Can those be changed to H3? Since they aren't highly important content it doesn't make sense to have them be at the same heading level as the accordions and other sections. On the beta site the heading levels are H3 for "Government information" and other footer links.
3. Zooming to 200% display was fine.

**Comment by danny-englander** [comment]
@amycole501 I've made updates based on your feedback. Can you retest at:

https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/

**Comment by amycole501** [comment]
When I use JAWS to skim for the different regions the search region shows up below the "main navigation" region. 

Visually on the page it shows up above it. Can it move?

Also, I hear "navigation navigation" twice in both the header and footer. USA.gov has this set up as well and it's repetitive. Can you somehow remove one of the navigations so it's not repeating itself? See screen shot to understand what I'm talking about on both points.
![vote-regions-jaws](https://user-images.githubusercontent.com/117778073/229174091-5dd2d3f0-e44c-4894-80e2-eb1c70dd114c.jpg)

**Comment by danny-englander** [comment]
Hi @amycole501 can you retest the navigations? The header should now announce as "Header primary navigation" and the footer should announce as "Footer navigation" As for the out of order items in the header, Ernie has said to pass on that one for now as we are putting most of our efforts into V2 now. Thanks! 

https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/

**Comment by danny-englander** [comment]
Ok I think we can close this as done!
