### ISSUE TITLE
Update the Date input field to use the USWDS Memorable date component

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#583]
**For USAGov Team**

As a benefits tool user, in order to successfully input my information, I would like the benefit tool's date input fields to be clearly defined, simple and inclusive.

Acceptance criteria:

- [ ] Update date input field to match USWDS inclusive patterns recommendations
- [ ] Bold "Your date of birth is" font, so it matches the style of other questions in that section

Resources:

- [Design review document](https://docs.google.com/document/d/1mssKCrkDqNA4GrD-FO22pK5ZifI43hXw88Z8AYvdO4I/edit?usp=sharing) (https://github.com/GSA/usagov-benefits-eligibility/issues/553)
- [Design prioritization spreadsheet](https://docs.google.com/spreadsheets/d/1JxpXDun8nagwVuYwc5a1PSZCPaGzhGcyJvIIYgX396s/edit?usp=sharing)
- [USWDS Inclusive Patterns](https://designsystem.digital.gov/patterns/create-a-user-profile/date-of-birth/)

Definition of Done:
- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [ ] Build process and deployment is automated and repeatable 
- [ ] Load testing/performance testing 
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)

**Comment by danny-englander** [comment]
Just adding that this would be the `Memorable date` component seen here: [https://designsystem.digital.gov/components/memorable-date/](https://designsystem.digital.gov/components/memorable-date/)
