### ISSUE TITLE
look into why pa11y doesn't run locally (but does on CI/CD)

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#587]
This is a little misleading because we know exactly where the problem lies:

https://github.com/GSA/usagov-benefits-eligibility/blob/main/pa11y.json#L4

When run on GitHub, the path listed here (`/usr/bin/google-chrome`) works just fine; however, if one doesn't have a browser (or a symlink to a browser) at that location, the step will fail.

That path was codified because without it, the pa11y tests were failing 100% of the time.  This issue on GitHub shows the behavior and the solution fixes it: https://github.com/pa11y/pa11y/issues/653

I don't know why (or even if) pa11y requires a hardcoded path as this would seem to make the tool somewhat fragile, particularly when used in different environments (which is what we've experienced).

One solution may be to create a symlink from where Chrome actually lives to where it's hardcoded.  Another may be to run a script that would look in all of the places for a browser and run whatever it finds or even create a symlink to that browser and tell pa11y to use the symlink.  Lots of options, not much fun to test.

Recommend using a virtualized or containerized approach as opposed to trying to run it on GitHub (by pushing commits to a branch and using the workflow dispatch).

**Comment by FatmaBakir** [comment]
`Docker-compose.yml` file has been added to the repo for local `pa11y` testing. This addresses any issues/impediments related with local `pa11y` configurations and testing.
