### ISSUE TITLE
Have Snyk run periodically (weekly?) instead of when PRs are updated

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#608]
At the moment, Snyk runs when the button on the Actions screen is pushed (it used to run when a PR was created / updated with new commits, but that was disabled in PR #607).  It would be helpful if we ran Snyk periodically (weekly?) instead of as a result of a PR modification.

Could it be run "in addition to" and not "instead of?"  Yes, absolutely.  The issue resolved in #607 was surfaced by Megalinter reports generating Megalinter reports [...] each of which resulted in a Snyk scan.  The additional Snyk scans at through our monthly allowance over the course of several hours.

Do we get anything by running it periodically rather than as a result of a change?  Yes.  If Snyk's data or tooling are updated (e.g., new vulnerabilities are discovered), we want to make sure we run them, even if our code hasn't changed.

Here's a link to the workflow ([.github/workflows/snky.yml](https://github.com/GSA/usagov-benefits-eligibility/blob/main/.github/workflows/snyk.yml))

Documentation on how to schedule actions: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

The updated snyk.yml file will look something like this...

```YAML
---
name: Snyk Scan

# yamllint disable-line rule:truthy
on:
  #  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 12 * * 1'
```

(the rest remains the same)

This will run the Snyk scan at 12:15pm (i.e., a quarter past noon) on every Monday.  This is the same syntax as one would see when editing a *nix crontab.

**Comment by wesley-dean-gsa** [comment]
@FatmaBakir, would you be open to working on this with me?  It's a comparatively low priority, but it may be a gentle way of gaining some familiarity with GitHub actions as they're used on the BEARS project.

**Comment by FatmaBakir** [comment]
@wesley-dean-gsa Sure! Thank you!
