### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#609]
### Description

The [Dockerfile](https://github.com/GSA/usagov-benefits-eligibility/blob/main/Dockerfile) needs to be updated so that it will build properly.

- [ ] `IMAGE_TAG` is currently `14` while the [.nvmrc](https://github.com/GSA/usagov-benefits-eligibility/blob/main/.nvmrc) specifies `16`  (.nvmrc tells `nvm` (Node Version Manager) which version of Node to use)

To build:

```shell
docker build -t bears_tester .
```

To run:

```shell
docker run --rm -it -p 3000:3000 bears_tester
```

Note: this is currently not working because of the 'undefined' issue encountered on #577

**Comment by FatmaBakir** [comment]
@wesley-dean-gsa Would you mind if I work on this quick task? I also would like to confirm that this task is regarding the fixing the Dockerfile and making sure it builds properly; independent of the  "http://localhost:3000undefined/" issue?
