### ISSUE TITLE
Set the demo URL to point to the demo branch

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#622]
### Description

After #621 is done, we can update the [Site Settings](https://pages.cloud.gov/sites/983/settings) to point the Demo site's branch name and URL to the newly-created branch and the new demo URL (benefits-tool-beta-demo.usa.gov), respectively.  

There may be a delay between when the change is made and when it's live.  I suspect that change will likely trigger a rebuild which takes roughly 2 minutes to complete.

Finally, test to see if everything works!

- [ ] site loads
- [ ] HTTPS / TLS certificate correctly matches and the site is able to load with any certificate-related warnings
- [ ] Rejoice!!

### User Story

#532

**Comment by FatmaBakir** [comment]
We have pointed the branch(release) to demo site url but the Pages support team required us to fill out "Federalist Site Info" form. It will take about a week for them to get back to us. And, there will be a security scan by GSA IT.

**Comment by FatmaBakir** [comment]
I've reached out to cloud.gov Pages support for follow-up. Their response is as per below - 1/31/20223:
"_We missed submitting initial launch scans but we are working with GSA IT now to get them done ASAP. Everything else is ready to go._"

**Comment by FatmaBakir** [comment]
This has been completed. Our demo site is running on `https://benefits-tool-beta-demo.usa.gov/death-of-a-loved-one/?` and no errors found.
