### ISSUE TITLE
Set the live URL to point to the new live release branch

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#624]
### Description

After the new release branch for the live site is created (#623), we'll want to update the site's configuration to point the live site URL at this new branch.

:warning:  Please exercise caution here.  Not only do the URL and branch settings need to be correct, but we need to communicate this change out

- [ ] before making the change
- [ ] while making the change
- [ ] after the change is made

By "before making the change," I don't mean immediately before -- I mean that we should communicate a few ways (Slack, standup, etc.) a few days before making this change.  This includes stakeholders (e.g., folks in the #10x-bears channel who may or may not be technical) as well as the rest of the team.  

The team communications ought to include the new deployment process (i.e., pushing commits to the new release branch) so that folks know how to make changes if needed.

Note: "pushing commits to the new release branch" may involve creating a PR **from** main **to** the new release branch.  It's also possible to automate this process via a GitHub Action / Workflow that is triggered by the creation of a new [release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) that would [force-push the commits](https://stackoverflow.com/questions/4351723/how-to-create-a-release-branch-in-git).

By "while making the change," I mean give people a heads-up so that they know a change is about to happen.

By "after making the change," I mean communicating to stakeholders that the change has been made and update the documentation to reflect the new process (i.e., pushing commits to the new release branch).

### User Story

#534

**Comment by FatmaBakir** [comment]
I've moved this to _blocked_ as it will be best to work on the live site once the demo site configurations are all set and stable per @wesley-dean-gsa's advice.

**Comment by FatmaBakir** [comment]
This is scheduled for **_10 AM EST, Tuesday, 2/21/2023_** and the communication has been passed to stakeholders by @erniedeeb.

**Comment by FatmaBakir** [comment]
https://benefits-tool-beta.usa.gov/ is now tied to `prod` branch.
https://benefits-tool-beta.usa-demo.gov/ is now tied to `release` branch.
`main` branch will be available through preview site urls.
