### ISSUE TITLE
Update pa11y scan to allow permission to comment on PRs

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#637]
### Description

The pa11y tests are failing with an `Error: Resource not accessible by integration`; the [Bump parse-url action is a good, recent example](https://github.com/GSA/usagov-benefits-eligibility/actions/runs/4068995229/jobs/7008213956#step:10:19).

The step that's failing was documented as a GitHub [issue](https://github.com/thollander/actions-comment-pull-request/issues/181) after Dependabot bumped the action from v2.3.0 to 2.3.1.

The recommended action is to add two lines of configuration to the [workflow](https://github.com/GSA/usagov-benefits-eligibility/blob/main/.github/workflows/pa11y.yml#L16):

```YAML
  permissions:
    pull-requests: write
```

That should go immediately after the `runs-on` line (line 16) such that `permissions` and `runs-on` are indented to the same level (so, the `pull-requests: write` line should be indented one more level (two spaces)).

There's [documentation on GitHub](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions) explaining the `permissions` section.

**Comment by FatmaBakir** [comment]
@wesley-dean-gsa Thank you for the detailed explanation of the issue and the solution to it. On it.
