### ISSUE TITLE
[Bug] [on hold] fonts are not loading properly

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#647]
### What's expected

Fonts are to be loaded properly and not return 404 (page not found) errors resulting from font files not being in the correct location.

### What happened

The URLs of the fonts are not correct -- we're seeing `url(fonts/blah/)` instead of `url(_nuxt/fonts/blah)`

`https://benefits-tool-beta.usa.gov/_nuxt/css/fonts/sourcesanspro-regular-webfont.e7bccfa.woff2` 

should be:

`https://benefits-tool-beta.usa.gov/_nuxt/fonts/sourcesanspro-regular-webfont.e7bccfa.woff2`

(no `css/`)

### How to replicate

https://gsa-tts.slack.com/archives/C04LF0T0V1N/p1675786831987839

### Here are some ideas for a more backend type fix

1. Branch dependent path changes (short term, fragile)
2. Investigate why Nuxt is generating these paths and fix it (long term, definitive)
3. Have the fonts live on the CDN somewhere to keep them constant (long term, requires additional consideration)

### Here are some resources for a potential fix from the front-end perspective

- [Nuxt.js is not importing font-face properly](https://stackoverflow.com/questions/62133278/nuxt-js-is-not-importing-font-face-properly)
- [Nuxt.js include font files: use static or assets?](https://stackoverflow.com/questions/50674972/nuxt-js-include-font-files-use-static-or-assets)
- [Loading custom font in Nuxt + Tailwind project](https://stackoverflow.com/questions/61425153/loading-custom-fonts-in-nuxt-tailwind-project)
- [Google search: nuxt does not load fonts](https://www.google.com/search?q=nuxt+does+not+load+fonts&oq=nuxt+does+not+load+fonts&aqs=chrome..69i57.5461j0j1&sourceid=chrome&ie=UTF-8)
- [Nuxt Font Loader on npm](https://www.npmjs.com/package/nuxt-font-loader)

**Comment by wesley-dean-gsa** [comment]
This was resolved in #648

**Comment by wesley-dean-gsa** [comment]
works correctly on the preview sites, but the live site now has these URLs:

`https://benefits-tool-beta.usa.gov/_nuxt/css/_nuxt/fonts/Latin-Merriweather-Regular.a30c1b8.woff2`

(the `css/` part needs to go)

**Comment by wesley-dean-gsa** [comment]
@r-bartlett-gsa @erniedeeb FYI, quick recap from our conversation about the current state of this issue:

1. live site looks as-expected and fonts load properly
2. preview sites look a little off as fonts are not being loaded properly
3. things "used to work" before #577 ; however, the resolution of that ticket introduced a variation in the way paths are generated such that the deployment script was no longer "fixing" things correctly (it works with live or preview, but not both; fixing one breaks the other)
4. it's less good to have preview sites rendered incorrectly on account of automated regression testing planned for the near future
5. we identified a few options:
  a. introduce shell logic to modify the paths based on which branch is being deployed
  b. determine how to set the font paths using Nuxt so that we do not need to modify font paths in the CSS
  c. publish the fonts to a CDN or static hosting mechanism and update the CSS to point to that static location

For option a:
The [Pages documentation on environment variables](https://cloud.gov/pages/documentation/env-vars-on-pages-builds/) mentions `${BRANCH}` environment variable that we may be able to use to modify the paths based on live vs preview deployments.

The logic would look like this:

```bash
[[ $BRANCH =~ (main|release) ]] && ( sed -i~ -Ee 's/update path for live/' *.css ) || ( sed -i~ -Ee 's/update path for preview/' *.css )
```

and the [package.json](https://github.com/GSA/usagov-benefits-eligibility/blob/main/package.json#L20) file's `.script.federalist` section would be where that logic would live

**Comment by FatmaBakir** [comment]
This issue has been resolved with our branch based federalist script as referred in #672 .
` if [ \"${BRANCH}\" = \"prod\" ] || [ \"${BRANCH}\" = \"release\" ]; then sed -i~ -Ee 's|(/?)fonts/|\\1../fonts/|g' *.css; else perl -pi -e 's/\\/fonts\\//\\/_nuxt\\/fonts\\//g' *.css; fi `
