### ISSUE TITLE
Add the CrossSell component back in when all translations have been completed

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#652]
### Description

In the multi-life event / new beta.usa.gov wrapper version of the application, we will remove the CrossSell component per @erniedeeb until all translations have been done for retirement and disability. 

### User Story
As a developer, I need to add the CrossSell component back in once all translations for retirement and disability have been completed for the new beta.usa.gov wrapper  / multi-life event version of the application.

## Branches
with CrossSell: https://github.com/GSA/usagov-benefits-eligibility/tree/multi-life-event-2023-cross-sell
without CrossSell: https://github.com/GSA/usagov-benefits-eligibility/tree/multi-life-event-2023

**Comment by r-bartlett-gsa** [comment]
@danny-englander I might be misunderstanding the purpose of this ticket/issue, but I thought I'll mention it anyways :) If a single-life-event version is enabled, the cross selling banners already do not display. The cross selling banners display only if multi-life event version is enabled, which only should be done when Spanish content is uploaded; and at that point you can still control these banners for each individual life event via markdown files. Please let me know if this does not make sense, and I will be happy to discuss this.
cc: @erniedeeb

**Comment by danny-englander** [comment]
@r-bartlett-gsa The point of this ticket is to have the beta wrapper implemented which was started by Frank in the multi-life event version, thus I have 2 branches based on that as per above. Let me know if you need further clarification or if I can help you understand this better.

**Comment by danny-englander** [comment]
Also see https://github.com/GSA/usagov-benefits-eligibility/commit/71995f2b61036fcb2f34b8b61dc6e2695db0ca36 for reference.
