### ISSUE TITLE
Fix broken source links

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#664]
Update benefits source links in benefits content.
CMS Medicare Retirement
CMS Medicare with Disability
SSA Retirement Benefits
DOL Coal Mine Workers Compensation
DOI Financial Assistance and Social Services for Burial

**Comment by r-bartlett-gsa** [comment]
Pull request #665

**Comment by danny-englander** [comment]
Approved and merged into main
