### ISSUE TITLE
[Bug] Redirects in multi-life event version cause language switching to be unreliable

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#680]
### What's expected

when clicking the language switcher button the top of the page, you should always just switch languages, not end up at https://beta.usa.gov/life-events

### What happened

when clicking the language switcher button the top of the page in the multi-life event version, you are often redirected (incorrectly) to https://beta.usa.gov/life-events

### How to replicate

1. Go to https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/
2. Keep trying to switch languages several times and sooner or later, you will be redirected to https://beta.usa.gov/life-events
3. This is incorrect, you should always just end up at the language you chose for a given page, for example https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/es/death-of-a-loved-one/?

### Proposed solutions
Remove global redirects since they were wreaking havoc when regular link buttons were clicked and implement a proper nuxt middleware direct.

**Comment by r-bartlett-gsa** [comment]
@danny-englander This might be related to #479 issue and #618 PR

**Comment by danny-englander** [comment]
@r-bartlett-gsa The issue described herein only started to happen once those redirects started to happen and with https://github.com/GSA/usagov-benefits-eligibility/pull/618 and https://github.com/GSA/usagov-benefits-eligibility/pull/618, those were against the single life event version and indeed fixed that issue. By contrast, here we are in the multi-life event version with the newly added redirects so I don't think this is related at all those those. I believe this to be a new issue because of the redirects and our team has indeed confirmed the steps above.

**Comment by danny-englander** [comment]
@r-bartlett-gsa Would you have an idea why these redirects were added directly in the application? They are all hard coded to https://beta.usa.gov/life-events

**Comment by r-bartlett-gsa** [comment]
@danny-englander It could be related to the work done in #579, please also see comments thread in that issue. There was a need to eliminate BEARS landing page for multi-life event mode and temporarily redirect the non-ready life events; we agreed to redirect to https://beta.usa.gov/life-experiences

**Comment by danny-englander** [comment]
@nehemiah-abuga Ready for testing. 

1. Pull `multi-life-event-2023` to your local
2. run `npm i`
3. run `npm run dev`
4. go localhost
5. keep trying to switch between English and Spanish using the language switcher button 3 or 4 times. 
6. You should not be redirected to https://beta.usa.gov/life-experiences

**Comment by nehemiah-abuga** [comment]
I have verified this fix and the issue is resolved.
