### ISSUE TITLE
[Refactor] new header menu should be a loop

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#684]
### User Story

As a developer, I need to simplify the new header menu into a loop. 

### Description

In the multi-life event version of the application, the new header menu should be a loop and not individually hardcoded. Doing this will make the code:

1. DRY (Do not repeat yourself)
2. Shorter
3. Easier to maintain

Here is the current code: https://github.com/GSA/usagov-benefits-eligibility/compare/main...579-nav-changes#diff-83e8a3432a09a97279997b583856e373eb1dda6f55f6e7a532b7541cc6a79b31R79-R123

Noting that we have already done this with the new footer menu, e.g. https://github.com/GSA/usagov-benefits-eligibility/blob/multi-life-event-2023/components/BetaUsaGovFooterNav.vue#L22-L33

### Proposed Fix
Follow the data structure for the provided footer menu example and do the same for the header menu.

**Comment by danny-englander** [comment]
@nehemiah-abuga Ready for testing

- [ ] Pull `multi-life-event-2023` to your local
- [ ] run `npm i`
- [ ] Run `npm run dev`
- [ ] Go to http://localhost:3000
- [ ] Inspect the main navigation, `li.usa-nav__primary-item` 
- [ ] ensure that each id is unique, for example `item-id-mnav-10`
- [ ] Now switch to spanish and follow the same steps above

**Comment by nehemiah-abuga** [comment]
I have verified this change in local. It looks good
