### ISSUE TITLE
Update mobile navigation

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#689]
### Description

In the new beta wrapper / multi life event version, we need to update the mobile navigation since it has changed on beta.usa.gov

### User Story
As a developer, I need to update the mobile navigation to match beta.usa.gov for our beta wrapper / multi life event version

**Comment by danny-englander** [comment]
Noting that there is now a discussion revolving with this in terms of the mobile nav menu items not matching the widescreen menu items so I moved this into blocked for now.

**Comment by erniedeeb** [comment]
Currently discussing with various usa.gov stakeholders to better understand navigation strategy which we can use to decide how to proceed.

**Comment by erniedeeb** [comment]
Closing in favor of [this issue](https://github.com/orgs/GSA/projects/48/views/2?pane=issue&itemId=27162623).
