### ISSUE TITLE
Change URLs to remove "beta"

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/usagov-benefits-eligibility#720]
### Description

Production and demo environment include beta in the URL to reflect the former beta state of usa.gov. Now that usa.gov is out of beta, we should update the URLs accordingly.

### User Story

benefits-tool-beta.usa.gov
benefits-tool-beta-demo-usa.gov

should be updated to:

benefits-tool.usa.gov
benefits-tool-demo.usa.gov

### Architectural Decision Records (ADRs)

Redirects should be made to direct traffic from the former beta URL to the new non-beta URL.

**Comment by FatmaBakir** [comment]
@erniedeeb 

Russell has put in a ticket for us to `ServiceNow tickets for the GSA IT DNS team` for the new DNS request.

As for the redirects, please see below Russell's comment:
`if you do want redirects, you may need to get creative about a technical approach since I don't believe [Cloud.gov](http://cloud.gov/) Pages has any native domain redirection capabilities.  You cold create a new site for the beta domain that uses meta refreshes to get the job done, I think but might not be worth the hassle.`

**Comment by FatmaBakir** [comment]
A note from Russell today:

> _Hi, just a heads up I submitted the ticket but later than I had planned.  It's going through the approval process so I'll probably have an update for you next week._

**Comment by erniedeeb** [comment]
Per Russell:

> The DNS records for [benefits-tool.usa.gov](http://benefits-tool.usa.gov/) and [benefits-tool-demo.usa.gov](http://benefits-tool-demo.usa.gov/) have been created so you folks should be able to get them setup now in Cloud.gov Pages.  If you run into any issues, the Cloud.gov Pages team should be able to help you out.

**Comment by FatmaBakir** [comment]
I emailed **_pages-support@cloud.gov_** this AM to get support for the DNS Name Change.

**Comment by FatmaBakir** [comment]
Pages Support team emailed the below:

> Since these are new domains to [cloud.gov](http://cloud.gov/) Pages, I do need you all to fill out our site launch form for compliance purposes:
> [form](https://docs.google.com/forms/d/1ujDu9mUNmHuCG2Mx5JYFUaXthYrf304yMpBrGOEudMA/edit)
> 
> Once that has been submitted, and reviewed by GSA IT, I can provision the new domains and you should be set.

I completed the forms. We need to talk about the production switch over timeline after I hear back from the Support Team.

**Comment by FatmaBakir** [comment]
I followed up with the Pages Support as per below thread:



![Image](https://user-images.githubusercontent.com/81575505/235496946-74e454f6-0dd9-4de3-b77e-32d43fbf8766.png)
