### ISSUE TITLE
Replace header beta logos with standard logos

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#721]
### User Story
As a developer, I need to replace the header logos for English and Spanish to match the new production usa gov site

### Description
Replace header beta logos with standard logos. Get the latest logos from the new usa.gov live site

**Comment by danny-englander** [comment]
@nehemiah-abuga This is ready for QA. 

## steps 

- [ ] 1. Pull `multi-life-event-2023` to your local
- [ ] 2. run `npm i`
- [ ] 3. Run `npm run dev`
- [ ] 4. Go to http://localhost:3000/
- [ ] 5. Inspect header logo and ensure it matches what is on https://www.usa.gov/
- [ ] 6. Switch language to Spanish
- [ ] 7. Inspect header logo and ensure it matches what is on https://www.usa.gov/es

**Comment by nehemiah-abuga** [comment]
I am seeing differences between local 3000 and usagov

Local
![image](https://user-images.githubusercontent.com/121119072/231178215-31c58454-70e8-45ff-a6b9-70db1dd804dd.png)

usa.gov 
![image](https://user-images.githubusercontent.com/121119072/231178417-5ac3e89a-19e8-41b5-8e67-6949fa048175.png)

**Comment by erniedeeb** [comment]
The logo link should point to `usa.gov`, right now it points to `usa.gov/life-events`

**Comment by danny-englander** [comment]
Logo sizes fixed for desktop and mobile and links updated as well. 

https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/

**Comment by brunerae** [comment]
@nehemiah-abuga tagging for a last check

**Comment by nehemiah-abuga** [comment]
I have verified the logos match. This can be deployed to PROD

**Comment by erniedeeb** [comment]
LGTM
