### ISSUE TITLE
Remove beta header message

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#724]
### User Story

As a developer, I need to remove the beta header message

### Description

We need to remove the beta header message

```
This is a beta site. It's an early, in-progress version of an improved USA.gov . If you don't find what you're looking for, return to the main site.
```

**Comment by brunerae** [comment]
@nehemiah-abuga tagging for a final check - please move to 'ready for deployment' once confirmed

**Comment by nehemiah-abuga** [comment]
@brunerae @scottqueen-bixal  - We don't have the theme build in https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/es/death-of-a-loved-one/

I am seeing this page

![image](https://user-images.githubusercontent.com/121119072/233514887-86834c4e-74c7-43fc-8a62-15bca1b23455.png)

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga are you able to just go to https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/ and toggle the spanish version from the UI?

**Comment by nehemiah-abuga** [comment]
I am to validate this when I toggle the Spanish version.
