### ISSUE TITLE
Investigate URL redirects from beta domain to the new domain

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/usagov-benefits-eligibility#728]
### Description

beta.USAGov became USAGov. Along with that change, the BEARS app is changing its dns names as below:

`https://benefits-tool-beta.usa.gov/ ==> https://benefits-tool.usa.gov/`
`https://benefits-tool-beta-demo.usa.gov/ ==> https://benefits-tool-demo.usa.gov/`

We'd like to know the level of effort needed to redirect url from the beta domain to the new domain. `Cloud.gov Pages` doesn't provide a native solution to redirect so there is a technical workaround needed to accomplish this. 

### User Story

-

### Architectural Decision Records (ADRs)

Evaluate the level of effort.

**Comment by erniedeeb** [comment]
Going to close this one for now @FatmaBakir let me know if you want to reopen it for any reason.
