### ISSUE TITLE
Initiate a POAM logging

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/usagov-benefits-eligibility#732]
### Description

Initiate a POAM (Plan of Action and Milestones) document listing all the security findings and steps to remediate them.

Code Scanning results can be seen [here](https://github.com/GSA/usagov-benefits-eligibility/security/code-scanning)

Sample Megalinter Trivy results can ben seen [here](https://github.com/GSA/usagov-benefits-eligibility/actions/runs/4724049755/jobs/8380780213)

**Comment by scottqueen-bixal** [comment]
this was merged into main https://github.com/GSA/usagov-benefits-eligibility/pull/736
