### ISSUE TITLE
Create Pipeline Diagram for V2 Architecture

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/usagov-benefits-eligibility#739]
### Description

Start working on a Pipeline Architecture Design for V2.

**Comment by FatmaBakir** [comment]
Created the 1st draft and shared with @scottqueen-bixal for review.

**Comment by FatmaBakir** [comment]
It's reviewed and additional modification made. Now, it's being reviewed by @gchi25 .

**Comment by fongcindy** [comment]
Completed, but will need review from GSA.

**Comment by FatmaBakir** [comment]
Updated diagram is [here](https://drive.google.com/file/d/1nohhvyxxF2Ozn6oAy--lTchPkVnXHq6V/view?usp=sharing) to be reviewed by USAGov team.

**Comment by FatmaBakir** [comment]
Russell has approved it per our collabaration document.
