### ISSUE TITLE
Button & Color inconsistency w/USAGov

### ISSUE THREAD

**Issue by diegocob** [GSA/usagov-benefits-eligibility#758]
### What's expected

Match the BEARS colors with USAGov.  

### What happened

Match the colors of the BEARS and USAGov:
i. BEARS current colors: 
a) "Close all" button color, background color in the questions, some text, and the benefits accordion varies: #1A4480 and #11385B.
d) Red Title color not mathing USAGov: #D83933

ii. Match with USAGovs:
a) "Español" and dark blue background color and text: #112F4E 
b) Red Title color: #C61F0C

### How to replicate

- [ ] Test hex colors in text, icons, shapes and buttons in BEARS.

**Comment by brunerae** [comment]
Closing because this was determined to be a non-issue.
