### ISSUE TITLE
Match Breadcumb with USAGov

### ISSUE THREAD

**Issue by diegocob** [GSA/usagov-benefits-eligibility#759]
### What's expected

Match BEARS breadcrumb with USAGov.

### What happened

BEARS breadcrumb is a different style (font, color, and underlining) than USAGov. 

### How to replicate

Match breadcrumb style and font with USAGov
- [ ] Color matches with USAGov
- [ ] Font type matches
- [ ] Style (size and underlining) matches
- [ ] ">" Symbol pointing in the same direction

**Comment by brunerae** [comment]
Need to confirm if this is still an issue - Diego flagged while looking at an old build because he wasn't able to see the new build.

**Comment by erniedeeb** [comment]
The issue is actually that the QA build doesn't have the breadcrumbs at all. And since we're not certain of the IA at this point, I think it's fair to exclude the breadcrumbs for the future v1 iterations and look to implement it in a more holistic way with usa.gov as part of the v2 work.
