### ISSUE TITLE
Communicate our DNS change to USAGov Team

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/usagov-benefits-eligibility#773]
### Description

This ticket is related with #720 

BEARS app has changed its [URL](https://benefits-tool.usa.gov/death-of-a-loved-one/?) to [benefits-tool.usa.gov](https://benefits-tool.usa.gov/death-of-a-loved-one/?). USAGov team needs to update their links pointing our application wherever applicable. This needs to be communicated to the USAGov team.

One example can be seen here:
https://www.usa.gov/government-death-benefits

**Comment by erniedeeb** [comment]
Links on usa.gov have been updated. I also spoke with Renata to update the link on 10x website.
