### ISSUE TITLE
Miner Criteria Not Displaying Properly in Retirement (Spanish) Page

### ISSUE THREAD

**Issue by nickpistone** [GSA/usagov-benefits-eligibility#798]
### What's expected

In the left sidebar where the applicant selects different criteria about themselves, the one related to working in a mine and black lung disease should be displaying in Spanish like this "Los fallecidos trabajaban en la industria minera del carbón y su muerte se debió a una neumoconiosis (enfermedad del pulmón negro)." 

### What happened

<img width="1055" alt="Screenshot 2023-05-08 at 1 29 26 PM" src="https://user-images.githubusercontent.com/121254111/236898325-0f4acd25-3fc5-446e-a7da-6243329cee6e.png">

"criteria.applicant_miner.label" is displaying instead of the correct text.

### How to replicate

Go to this URL (https://benefits-tool.usa.gov/es/retirement/?) and scroll down on the left sidebar in the gray section below (Acerca de Usted). The 5th option says "criteria.applicant_miner.label."

**Comment by diegocob** [comment]
Closing this issue, since it is resolved on the testing site.

**Comment by scottqueen-bixal** [comment]
This has been approved and merged in. Updated status to tag for release.
