### ISSUE TITLE
Collaboration on Cypress Test Automation

### ISSUE THREAD

**Issue by FatmaBakir** [GSA/usagov-benefits-eligibility#812]
As the DevOps Engineer on the team, I need to help the QA to automate the Cypress testing; get the pipeline working as per his plan.

UPDATE: I will work on a dynamic, branch based solution to pull `baseurl` value for the cypress testing.

**Comment by FatmaBakir** [comment]
I've worked on a github action file that automates the cypress test. It's currently working/passing; currently gets triggered manually.

More work can be needed depending on the final cypress design and architecture; pending Nehemiah's work.

- How should it be triggered? `push` on certain branches, `pull-request`, or `manual`, or all?
- Which 'baseurl' should we use to run the test on?
- Any other condition necessary?

JFYI - @nehemiah-abuga @scottqueen-bixal

**Comment by scottqueen-bixal** [comment]
> * How should it be triggered? `push` on certain branches, `pull-request`, or `manual`, or all?
> * Which 'baseurl' should we use to run the test on?

I'd suggest `pull-request` so it is set up as a gate for any upstream movement. 

We likely want to run these tests against a containerized version of the application, this way it runs the same on every PR.  This would put the `baseurl` set to `localhost:<port>`

**Comment by nehemiah-abuga** [comment]
I have verified that the branch is populated in the site prefix. Here are the results for the run
https://github.com/GSA/usagov-benefits-eligibility/actions/runs/5005508991/jobs/8969567092

Thanks for your help @FatmaBakir
