### ISSUE TITLE
Revise KPIs

### ISSUE THREAD

**Issue by nickpistone** [GSA/usagov-benefits-eligibility#832]
After first wireframes are done, update strategy/action, hypothesis, and KPIs columns.

**Comment by nickpistone** [comment]
As we get further in user testing, we will be able to make our hypotheses more specific. As the wireframes become more developed, we can define the KPIs more concretely around measurable actions.

**Comment by fongcindy** [comment]
Potential additional user testing would help with validating hypothesis

**Comment by nickpistone** [comment]
For this ticket, I will be adding in more specificity to the hypotheses and design/strategy columns to align with what we currently know about the prototype. However, I will need to wait until a future sprint to get more granular on the hypotheses and KPIs. The goal is to use user testing to come up with hypotheses for where users are getting stuck or confused and then using quantitative data to validate our interpretations of what we observe in user testing.

**Comment by nickpistone** [comment]
This is done.
