### ISSUE TITLE
e2e tests to validate links

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/usagov-benefits-eligibility#883]
### User Story

As a visitor to the site, I want to ensure that I can successfully native to any links within the page.

As a QE I want to integrate an e2e test that will :

Test the links within the pages to ensure successful 200 response from the links that I visit within the page

**Comment by scottqueen-bixal** [comment]
@nehemiah-abuga we have a related ticket that needs to be resolved for getting these tests to pass on our checks - can you link that ticket here in the comments for tracking?
