### ISSUE TITLE
Accessibility Statement

### ISSUE THREAD

**Issue by amycole501** [GSA/usagov-benefits-eligibility#888]
While USA has its own accessibility statement, it is recommended that we create a path for disabled form users to reach out for help specifically with the benefits forms. USA a11y team members may be unfamiliar with the BEARS project and wouldn't be in a position to fully support users who may encounter accessibility blockers given the tight turnaround we're working on for delivery. Providing a pathway for support is recommended by Section 508 https://www.section508.gov/manage/laws-and-policies/website-accessibility-statement/

**Comment by EnriqueOrt** [comment]
@amycole501 - what is a good timeline to get this started? Any chance we can work with/align with USAgovs policy? Thanks in advance for the update!

**Comment by amycole501** [comment]
this was put on hold since we weren't sure we needed it; USA has a statement already https://www.usa.gov/accessibility-policy 
The concern was when we move into a CMS situation with the content and if their statement still applies to BEARS.

**Comment by EnriqueOrt** [comment]
@amycole501 - Accessibility statement is available and you can create a pull request if needed to update. Would it be safe to mark this as completed? Will wait for your input.
