### ISSUE TITLE
Link under Beneficios de jubilación section in es/retirement page is failing

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/usagov-benefits-eligibility#889]
### Bug

Link under Beneficios de jubilación section in es/retirement page is failing

## Steps to reproduce

- Navigate to https://benefits-tool.usa.gov/es/retirement/?
- Expand Beneficios de jubilació accordion
- Click the link in Cómo presentar una solicitud (en inglés)

![Image](https://github.com/GSA/usagov-benefits-eligibility/assets/121119072/48a693f8-1c59-4743-81ef-90350e165d2b)

**Comment by EnriqueOrt** [comment]
Diego to provide an update week June 26th. On track

**Comment by diegocob** [comment]
@nehemiah-abuga, I made this change. I couldn't check the change in the cloud testing envi. Could you please QA it and see if it's ready to deploy?

**Comment by diegocob** [comment]
@scottqueen-bixal, has this been deployed?
