### ISSUE TITLE
Cypress e2e Cross browser testing V1

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/usagov-benefits-eligibility#913]
### User Story

As a Visitor to the site, I want to access various functionalities with the site using different browsers. The browsers in scope are Chrome, Edge, Firefox.
As a QE I want to integrate the tests to be run on  Chrome, Edge, and Firefox browsers to ensure functionality of the site is similar in different browsers

**Comment by EnriqueOrt** [comment]
On track for Sprint 10

**Comment by scottqueen-bixal** [comment]
includes: edge, chrome, firefox
