### ISSUE TITLE
benefits-tool-beta.usa.gov and benefits-tool.usa.gov stuck in redirect loop on mobile (iOS)

### ISSUE THREAD

**Issue by erniedeeb** [GSA/usagov-benefits-eligibility#936]
On iOS (both Chrome and Safari) `benefits-tool.usa.gov` and `benefits-tool-beta.usa.gov`  appear to be stuck in redirect loop. Expected behavior is that the URL without directory redirects to `benefits-tool.usa.gov/death-of-a-loved-one` or `benefits-tool-beta.usa.gov/death-of-a-loved-one`

This issue was reproduced on 3 iOS devices but cannot be recreated on 2 Android devices.

**Comment by scottqueen-bixal** [comment]
The issue seems to be related to a nuxt configuration for our root redirects.  I've pushed up a testable fix here   https://github.com/GSA/usagov-benefits-eligibility/pull/937

We will continue to test , and if all good, we will deploy during time when pages support can be available.

**Comment by scottqueen-bixal** [comment]
deployed to production, follow up task to investigate doing some cross browser testing with cypress https://github.com/orgs/GSA/projects/48/views/10?pane=issue&itemId=33570731
