### ISSUE TITLE
Disability page “Concurrent Retirement and Disability Payments (CRDP)” eligibility criteria displaying incorrectly for selected filter option.

### ISSUE THREAD

**Issue by nehemiah-abuga** [GSA/usagov-benefits-eligibility#949]
### Description

Disability page “Concurrent Retirement and Disability Payments (CRDP)” eligibility criteria displaying incorrectly for selected filter option.

### Steps to reproduce
Select the options in the query https://benefits-tool.usa.gov/disability/?77edd0d=yes&b95c6d4=7-25-1963&8c5fff1=1&2fe2b3a=yes&633dad2=a+member+of+the+National+Guard%2FReserve and validate that the eligibility criteria is displaying correctly

Given “a member of the National Guard/Reserve” option is selected, the eligibility criteria for this option should have a green check mark instead of it being red crossed out.

The same issue is also on the disability Spanish page. For this select “retirado del servicio” option

https://benefits-tool-demo.usa.gov/es/disability/?b95c6d4=7-25-1963&8c5fff1=1&2fe2b3a=s%C3%AD&633dad2=retirado+del+servicio

### Actual Results

![Image](https://github.com/GSA/usagov-benefits-eligibility/assets/121119072/da0f8364-48d5-4196-b1cd-59a7e4ec350f)

![Image](https://github.com/GSA/usagov-benefits-eligibility/assets/121119072/f81d883e-fc60-4849-8dae-f04179f335bc)

**Comment by diegocob** [comment]
@scottqueen-bixal, I didn't get what the two options were. I understand that the criteria has to match so that it's marked as a green check when it's selected.

**Comment by diegocob** [comment]
@nehemiah-abuga we had a meeting with @EnriqueOrt and @fongcindy. The UI needs to match the criteria. 

1. In the Disability and Retirement pages, when someone selects “a member of the National Guard/Reserve”, the eligibility criteria for this option should have a green check mark instead of it being red crossed out.

2. The same on the Disability and Retirement Spanish page. For this select “retirado del servicio” option.

**Comment by scottqueen-bixal** [comment]
This has been updated and QA'd on our end, ready for final review @EnriqueOrt

**Comment by EnriqueOrt** [comment]
Reviewed and approved. All information present and threads resolved. Thank you!
